import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { nationService } from '../../api/nation-service';
import {
  currencyCodeOptionsLoader,
  DEFAULT_CRUD_MODAL_WIDTH,
  languageCodeOptionsLoader,
} from '../api-module';

export const pageMeta = {
  name: 'Nation',
  title: '国家管理',
  description: '维护国家地区信息。',
} as const;

export const nationPageCrudConfig: CrudPageConfig = {
  apiBase: '/Nation',
  apiService: nationService,
  defaultFormValues: {
    enable: true,
    orderCode: 100,
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: 'id',
      label: '国家码',
      layoutGroup: 'basic',
      layoutGroupTitle: '国家信息',
      layoutOrder: 10,
      disabledOnEdit: true,
      fixed: 'left',
      required: true,
      search: true,
      showIdOnCreate: true,
      table: true,
      width: 120,
    },
    {
      key: 'cnName',
      label: '中文名',
      layoutGroup: 'basic',
      layoutOrder: 20,
      search: true,
      table: true,
      width: 140,
    },
    {
      key: 'enName',
      label: '英文名',
      layoutGroup: 'basic',
      layoutOrder: 30,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'iso3Letter',
      label: '3字母国家码',
      layoutGroup: 'basic',
      layoutOrder: 40,
      search: true,
      table: true,
      width: 140,
    },
    {
      key: 'telephoneAreaCode',
      label: '电话区号',
      layoutGroup: 'basic',
      layoutOrder: 50,
      search: true,
      table: true,
      width: 120,
    },
    {
      key: 'language',
      label: '语言',
      layoutGroup: 'basic',
      layoutOrder: 60,
      loadOptions: languageCodeOptionsLoader,
      search: true,
      table: true,
      type: 'select',
      width: 140,
    },
    {
      key: 'continent',
      label: '洲',
      layoutGroup: 'basic',
      layoutOrder: 70,
      search: true,
      table: true,
      width: 120,
    },
    {
      key: 'timezone',
      label: '时区',
      layoutGroup: 'basic',
      layoutOrder: 80,
      table: true,
      width: 180,
    },
    {
      key: 'currencyCode',
      label: '货币编码',
      layoutGroup: 'business',
      layoutGroupTitle: '货币与状态',
      layoutOrder: 10,
      loadOptions: currencyCodeOptionsLoader,
      search: true,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'currencyName',
      label: '货币名称',
      layoutGroup: 'business',
      layoutOrder: 20,
      table: true,
      width: 140,
    },
    {
      key: 'currencySymbol',
      label: '货币符号',
      layoutGroup: 'business',
      layoutOrder: 30,
      table: true,
      width: 100,
    },
    {
      key: 'enable',
      label: '是否启用',
      layoutGroup: 'business',
      layoutOrder: 40,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'orderCode',
      label: '排序代码',
      layoutGroup: 'business',
      layoutOrder: 50,
      type: 'number',
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '国家管理',
};
