import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { auditReportService } from '../../api/audit-report-service';
import {
  buildDictOptionsLoader,
  buildEnumOptionsLoader,
  DEFAULT_CRUD_MODAL_WIDTH,
  tenantOptionsLoader,
} from '../api-module';

export const pageMeta = {
  name: 'AuditReport',
  title: '审计报告',
  description: '查询审计对象、审计时间范围并查看审计服务生成的报告内容。',
} as const;

export const auditReportPageCrudConfig: CrudPageConfig = {
  apiBase: '/AuditReport',
  apiService: auditReportService,
  domainObject: true,
  allowCreate: false,
  allowEdit: false,
  allowDelete: false,
  allowRetrieve: true,
  defaultQuery: { pageIndex: 1, pageSize: 10 },
  fields: [
    {
      key: 'containsTitle',
      label: '标题',
      search: true,
      form: false,
      detail: false,
    },
    {
      key: 'id',
      label: '报告 ID',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    { key: 'title', label: '标题', table: true, width: 280 },
    {
      key: 'confidentialLevel',
      label: '机密等级',
      search: true,
      table: true,
      type: 'select',
      valueType: 'number',
      loadOptions: buildEnumOptionsLoader(
        'com.levin.commons.rbac.ConfidentialLevel',
      ),
      width: 140,
    },
    {
      key: 'targetType',
      label: '审计对象类型',
      search: true,
      table: true,
      type: 'select',
      loadOptions: buildDictOptionsLoader(
        'com.levin.oak.base.entities.AuditReport.targetType',
      ),
      width: 160,
    },
    {
      key: 'targetId',
      label: '审计对象标识',
      search: true,
      table: true,
      width: 200,
    },
    {
      key: 'bizType',
      label: '业务类型',
      search: true,
      table: true,
      type: 'select',
      loadOptions: buildDictOptionsLoader(
        'com.levin.oak.base.entities.AuditReport.bizType',
      ),
      width: 160,
    },
    {
      key: 'bizCategory',
      label: '业务类别',
      search: true,
      table: true,
      type: 'select',
      loadOptions: buildDictOptionsLoader(
        'com.levin.oak.base.entities.AuditReport.bizCategory',
      ),
      width: 160,
    },
    {
      key: 'gteStartTime',
      label: '审计开始时间起',
      search: true,
      detail: false,
      form: false,
      type: 'datetime',
    },
    {
      key: 'lteEndTime',
      label: '审计结束时间止',
      search: true,
      detail: false,
      form: false,
      type: 'datetime',
    },
    {
      key: 'startTime',
      label: '审计开始时间',
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'endTime',
      label: '审计结束时间',
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'createTime',
      label: '创建时间',
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'creator',
      label: '创建者',
      search: true,
      form: false,
    },
    {
      key: 'gteCreateTime',
      label: '创建时间起',
      search: true,
      detail: false,
      form: false,
      type: 'datetime',
    },
    {
      key: 'lteCreateTime',
      label: '创建时间止',
      search: true,
      detail: false,
      form: false,
      type: 'datetime',
    },
    {
      key: 'tenantId',
      label: '归属租户',
      search: true,
      type: 'select',
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      visibleForPlatformUser: true,
    },
    {
      key: '__tenant',
      label: '归属租户',
      table: true,
      detail: false,
      type: 'tenant',
      visibleForPlatformUser: true,
      width: 180,
    },
    { key: 'tenantName', label: '租户名称', detail: false, form: false },
    {
      key: 'orgId',
      label: '所属组织',
      form: false,
      type: 'org-tree-select',
    },
    { key: 'orgName', label: '组织名称', detail: false, form: false },
    { key: 'domainId', label: '领域标识', form: false },
    { key: 'editor', label: '编辑器', detail: false, form: false },
    {
      key: 'content',
      jsonSchemaEditor: true,
      jsonSchema: ':editor',
      label: '数据内容',
      // 报告正文由独立“查看报告”入口按 editor 渲染，记录详情不混入正文。
      detail: false,
      form: false,
      fullRow: true,
      type: 'json',
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      type: 'datetime',
    },
    { key: 'orderCode', label: '排序代码', form: false, type: 'number' },
    {
      key: 'enable',
      label: '是否启用',
      form: false,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      form: false,
      type: 'switch',
      valueType: 'boolean',
    },
    { key: 'remark', label: '备注', form: false, fullRow: true, type: 'textarea' },
    { key: 'optimisticLock', label: '乐观锁版本号', form: false },
  ],
  rowActions: [],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: pageMeta.title,
};
