import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { DEFAULT_CRUD_MODAL_WIDTH, tenantOptionsLoader } from '../api-module';

export const accessLogPageCrudConfig: CrudPageConfig = {
  apiBase: '/AccessLog',
  allowCreate: false,
  allowDelete: false,
  allowEdit: false,
  allowRetrieve: true,
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForSaasUser: true,
    },
    {
      key: '__tenant',
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForSaasUser: true,
      width: 180,
    },
    {
      key: 'id',
      label: '日志ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    { key: 'domain', label: '域名', search: true, table: true, width: 160 },
    { key: 'containsVisitor', label: '访问者', form: false, search: true },
    { key: 'visitor', label: '访问者', table: true, width: 140 },
    { key: 'containsTitle', label: '标题', form: false, search: true },
    { key: 'title', label: '标题', table: true, width: 180 },
    {
      key: 'logType',
      label: '日志类型',
      search: true,
      table: true,
      width: 120,
    },
    { key: 'containsBizKey', label: '业务主键', form: false, search: true },
    { key: 'bizKey', label: '业务主键', table: true, width: 160 },
    { key: 'containsBizType', label: '业务类型', form: false, search: true },
    { key: 'bizType', label: '业务类型', table: true, width: 140 },
    { key: 'containsRequestUri', label: '请求URI', form: false, search: true },
    { key: 'requestUri', label: '请求URI', table: true, width: 220 },
    { key: 'requestMethod', label: '请求方法', table: true, width: 120 },
    {
      key: 'responseStatus',
      label: '响应状态码',
      table: true,
      type: 'number',
      width: 120,
    },
    {
      key: 'containsRemoteAddr',
      label: '操作IP地址',
      form: false,
      search: true,
    },
    { key: 'remoteAddr', label: '操作IP地址', table: true, width: 140 },
    {
      key: 'gteCreateTime',
      label: '访问时间开始',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'lteCreateTime',
      label: '访问时间结束',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'headInfo',
      form: false,
      label: '头部信息',
      fullRow: true,
      type: 'textarea',
    },
    {
      key: 'requestParams',
      form: false,
      label: '请求参数',
      fullRow: true,
      type: 'textarea',
    },
    {
      key: 'requestBody',
      form: false,
      label: '请求体',
      fullRow: true,
      type: 'textarea',
    },
    {
      key: 'responseBody',
      form: false,
      label: '响应体',
      fullRow: true,
      type: 'textarea',
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '访问日志管理',
};
