import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { rbacPermissionItemService } from '../../api/rbac-permission-item-service';
import {
  DEFAULT_CRUD_MODAL_WIDTH,
  buildEnumOptionsLoader,
  roleOptionsLoader,
} from '../api-module';

const permissionCategoryOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.RbacPermissionItem$Category',
);
const permissionActionTypeOptionsLoader = buildEnumOptionsLoader(
  'com.levin.commons.rbac.ActionType',
);
const confidentialLevelOptionsLoader = buildEnumOptionsLoader(
  'com.levin.commons.rbac.ConfidentialLevel',
);

export const pageMeta = {
  name: 'RbacPermissionItem',
  title: '权限项定义',
  description: '维护权限项定义。',
} as const;

export const rbacPermissionItemPageCrudConfig: CrudPageConfig = {
  apiBase: '/RbacPermissionItem',
  apiService: rbacPermissionItemService,
  allowRetrieve: true,
  defaultFormValues: {
    category: 'Custom',
    editable: true,
    enable: true,
    ignored: false,
    isAndMode: false,
    onlyRequireAuthenticated: false,
    orderCode: 100,
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: 'id',
      label: '权限项ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'icon',
      layoutGroup: 'basic',
      layoutOrder: 70,
      label: '图标',
      type: 'image',
    },
    {
      key: 'inCategory',
      label: '类别',
      form: false,
      loadOptions: permissionCategoryOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'category',
      label: '类别',
      layoutGroup: 'basic',
      layoutGroupTitle: '权限资源',
      layoutOrder: 10,
      loadOptions: permissionCategoryOptionsLoader,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'domain',
      label: '资源域',
      layoutGroup: 'basic',
      layoutOrder: 20,
      required: true,
      search: true,
      table: true,
      width: 140,
    },
    {
      key: 'type',
      label: '资源类型',
      layoutGroup: 'basic',
      layoutOrder: 30,
      required: true,
      search: true,
      table: true,
      width: 160,
    },
    {
      key: 'res',
      label: '资源',
      layoutGroup: 'basic',
      layoutOrder: 40,
      search: true,
      table: true,
      width: 160,
    },
    {
      key: 'action',
      label: '操作',
      layoutGroup: 'basic',
      layoutOrder: 50,
      required: true,
      search: true,
      table: true,
      width: 120,
    },
    {
      key: 'actionTypes',
      label: '操作类型',
      fullRow: true,
      layoutGroup: 'basic',
      layoutOrder: 60,
      loadOptions: permissionActionTypeOptionsLoader,
      multiple: true,
      type: 'select',
    },
    {
      key: 'ignored',
      label: '是否忽略',
      layoutGroup: 'business',
      layoutGroupTitle: '访问策略',
      layoutOrder: 10,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'onlyRequireAuthenticated',
      label: '仅要求认证',
      layoutGroup: 'business',
      layoutOrder: 20,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 120,
    },
    {
      key: 'isAndMode',
      label: '匹配模式',
      layoutGroup: 'business',
      layoutOrder: 30,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'verifyExpression',
      label: '验证表达式',
      fullRow: true,
      layoutGroup: 'business',
      layoutOrder: 40,
      type: 'textarea',
    },
    {
      key: 'confidentialLevel',
      label: '数据保密级别',
      layoutGroup: 'business',
      layoutOrder: 50,
      loadOptions: confidentialLevelOptionsLoader,
      type: 'select',
      valueType: 'number',
    },
    {
      key: 'anyRoles',
      label: '任意角色',
      layoutGroup: 'business',
      fullRow: true,
      layoutOrder: 60,
      loadOptions: roleOptionsLoader,
      multiple: true,
      remoteSearch: true,
      type: 'role-select',
    },
    {
      key: 'anyUserTypes',
      label: '任意用户类型',
      layoutGroup: 'business',
      layoutOrder: 70,
      span: 2,
      type: 'tags',
    },
    {
      key: 'enable',
      label: '是否启用',
      layoutGroup: 'business',
      layoutOrder: 80,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      layoutGroup: 'business',
      layoutOrder: 90,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'remark',
      label: '备注',
      fullRow: true,
      layoutOrder: 10,
      type: 'textarea',
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '权限项定义',
};
