import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import {
  buildEnumOptionsLoader,
  DEFAULT_CRUD_MODAL_WIDTH,
  tenantOptionsLoader,
} from '../api-module';

const jobPostTypeOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.JobPost$Type',
);

export const jobPostPageCrudConfig: CrudPageConfig = {
  apiBase: '/JobPost',
  defaultFormValues: {
    editable: true,
    enable: true,
    orderCode: 100,
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  permissionResourceName: '工作岗位',
  permissionTypePrefix: '系统数据-',
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForSaasUser: true,
    },
    {
      key: '__tenant',
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForSaasUser: true,
      width: 180,
    },
    {
      key: 'id',
      label: '岗位ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    { key: 'containsCode', label: '编码', form: false, search: true },
    { key: 'containsName', label: '名称', form: false, search: true },
    { key: 'code', label: '编码', required: true, table: true, width: 140 },
    { key: 'name', label: '名称', required: true, table: true, width: 160 },
    {
      key: 'inType',
      label: '类型',
      form: false,
      loadOptions: jobPostTypeOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'type',
      label: '类型',
      loadOptions: jobPostTypeOptionsLoader,
      required: true,
      table: true,
      type: 'select',
      width: 120,
    },
    { key: 'containsPinyinName', label: '拼音名', form: false, search: true },
    { key: 'pinyinName', label: '拼音名', table: true, width: 160 },
    {
      key: 'gteCreateTime',
      label: '创建时间开始',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'lteCreateTime',
      label: '创建时间结束',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'enable',
      label: '是否启用',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    { key: 'orderCode', label: '排序代码', type: 'number' },
    { key: 'remark', label: '备注', type: 'textarea' },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '工作岗位管理',
};
