import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { servicePluginService } from '../../api/service-plugin-service';
import {
  DEFAULT_CRUD_MODAL_WIDTH,
  FILE_STORAGE_SINGLE_UPLOAD_PATH,
} from '../api-module';

export const pageMeta = {
  name: 'ServicePlugin',
  title: '服务插件管理',
  description: '维护服务插件。',
} as const;

export const servicePluginPageCrudConfig: CrudPageConfig = {
  apiBase: '/ServicePlugin',
  apiService: servicePluginService,
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  listTables: [
    {
      allowCreate: false,
      allowDelete: false,
      allowEdit: true,
      allowRetrieve: true,
      key: 'list',
      label: '服务插件列表',
      listPath: '/ServicePlugin/list',
      tableName: 'default',
    },
    {
      allowCreate: false,
      allowDelete: false,
      allowEdit: false,
      allowRetrieve: false,
      key: 'list2',
      listPath: '/ServicePlugin/list2',
      name: '服务插件列表-2',
      tableName: '服务插件列表-2',
      title: '表格2',
    },
    {
      allowCreate: false,
      allowDelete: false,
      allowEdit: false,
      allowRetrieve: false,
      key: 'list3',
      listPath: '/ServicePlugin/list3',
      name: '服务插件列表-3',
      tableName: '服务插件列表-3',
      title: '表格3',
    },
  ],
  fields: [
    {
      key: 'id',
      label: '插件ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'containsName',
      label: '名称',
      form: false,
      search: true,
    },
    {
      key: 'name',
      label: '名称',
      required: true,
      table: true,
      width: 180,
    },
    {
      key: 'containsCategoryName',
      label: '分类名称',
      form: false,
      search: true,
    },
    {
      key: 'categoryName',
      label: '分类名称',
      table: true,
      width: 140,
    },
    {
      key: 'containsGroupName',
      label: '分组名称',
      form: false,
      search: true,
    },
    {
      key: 'groupName',
      label: '分组名称',
      table: true,
      width: 140,
    },
    {
      key: 'containsPluginTypeName',
      label: '插件类型名称',
      form: false,
      search: true,
    },
    {
      key: 'pluginTypeName',
      label: '插件类型名称',
      form: false,
      table: true,
      width: 140,
    },
    {
      key: 'logo',
      label: 'Logo',
      form: false,
      table: true,
      type: 'image',
      uploadPath: FILE_STORAGE_SINGLE_UPLOAD_PATH,
      width: 120,
    },
    {
      key: 'expiredTime',
      label: '到期时间',
      form: true,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'enable',
      label: '是否启用',
      form: false,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      form: false,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'exInfo',
      label: '扩展信息',
      form: false,
      type: 'json',
    },
    {
      key: 'remark',
      label: '备注',
      form: false,
      fullRow: true,
      type: 'textarea',
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '服务插件管理',
};
