import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { electronicContractTemplateService } from '../../api/electronic-contract-template-service';
import {
  buildEnumOptionsLoader,
  DEFAULT_CRUD_MODAL_WIDTH,
  tenantOptionsLoader,
  userOptionsLoader,
  withModuleCrudConfig,
} from '../api-module';

const confidentialLevelOptionsLoader = buildEnumOptionsLoader(
  'com.levin.commons.rbac.ConfidentialLevel',
);

export const pageMeta = {
  name: 'ElectronicContractTemplate',
  title: '电子合同模板',
  description: '维护电子合同模板。',
} as const;

export const electronicContractTemplatePageCrudConfig: CrudPageConfig =
  withModuleCrudConfig({
    apiBase: '/EContractTemplate',
    domainObject: true,
    apiService: electronicContractTemplateService,
    defaultFormValues: {
      status: 'Draft',
    },
    fields: [
      {
        key: 'tenantId',
        label: '归属租户',
        layoutGroup: 'ownership',
        layoutGroupTitle: '归属信息',
        layoutOrder: 10,
        loadOptions: tenantOptionsLoader,
        remoteSearch: true,
        search: true,
        type: 'select',
        visibleForPlatformUser: true,
      },
      {
        key: 'orgId',
        label: '所属组织',
        layoutGroup: 'ownership',
        layoutOrder: 20,
        type: 'org-tree-select',
      },
      {
        key: 'ownerId',
        label: '所属用户',
        layoutGroup: 'ownership',
        layoutOrder: 30,
        loadOptions: userOptionsLoader,
        remoteSearch: true,
        type: 'select',
      },
      {
        key: 'id',
        label: '模板ID',
        form: false,
        search: true,
        table: true,
        width: 180,
      },
      {
        key: 'containsTemplateNo',
        label: '模板编号',
        form: false,
        search: true,
      },
      {
        key: 'templateNo',
        label: '模板编号',
        layoutGroup: 'basic',
        layoutGroupTitle: '模板信息',
        layoutOrder: 10,
        required: true,
        table: true,
        width: 180,
      },
      {
        key: 'name',
        label: '模板名称',
        layoutGroup: 'basic',
        layoutOrder: 20,
        required: true,
        table: true,
        width: 220,
      },
      {
        key: 'category',
        label: '类别',
        layoutGroup: 'basic',
        layoutOrder: 30,
        required: true,
        table: true,
        width: 140,
      },
      {
        key: 'title',
        label: '模板标题',
        form: false,
        search: true,
        table: true,
        width: 220,
      },
      {
        key: 'bizType',
        label: '业务类型',
        form: false,
        search: true,
        table: true,
        width: 140,
      },
      { key: 'contractCategory', label: '合同类别', layoutGroup: 'basic', layoutOrder: 40, table: true, width: 140 },
      { key: 'contractType', label: '合同类型', layoutGroup: 'basic', layoutOrder: 50, table: true, width: 160 },
      {
        key: 'confidentialLevel',
        label: '机密等级',
        layoutGroup: 'basic',
        layoutOrder: 60,
        loadOptions: confidentialLevelOptionsLoader,
        type: 'select',
        valueType: 'number',
        width: 130,
      },
      {
        key: 'fileName',
        label: '模板文件名',
        layoutGroup: 'media',
        layoutGroupTitle: '模板文件',
        layoutOrder: 10,
        required: true,
        table: true,
        width: 220,
      },
      { key: 'fileUrl', label: '模板文件链接', layoutGroup: 'media', layoutOrder: 20, required: true, span: 2 },
      { key: 'fileHash', label: '模板文件哈希', layoutGroup: 'media', layoutOrder: 30, width: 180 },
      { key: 'mimeType', label: '模板文件类型', layoutGroup: 'media', layoutOrder: 40, width: 180 },
      { key: 'signerRoleDefinition', label: '签署角色定义', layoutGroup: 'extension', layoutGroupTitle: '签署与字段配置', layoutOrder: 10, type: 'json' },
      {
        key: 'defaultSealPositionRules',
        label: '默认签章位置规则',
        layoutGroup: 'extension',
        layoutOrder: 20,
        type: 'json',
      },
      { key: 'templateFieldSchema', label: '模板字段定义', layoutGroup: 'extension', layoutOrder: 30, type: 'json' },
      { key: 'description', label: '模板描述', fullRow: true, layoutGroup: 'content', layoutGroupTitle: '模板说明', layoutOrder: 10, type: 'textarea' },
      {
        key: 'status',
        label: '模板状态',
        layoutGroup: 'business',
        layoutGroupTitle: '状态设置',
        layoutOrder: 10,
        search: true,
        table: true,
        width: 120,
      },
      { key: 'versionNo', label: '版本号', layoutGroup: 'business', layoutOrder: 20, table: true, width: 100 },
      {
        key: 'createTime',
        label: '创建时间',
        form: false,
        table: true,
        type: 'datetime',
        width: 180,
      },
    ],
    modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
    title: '电子合同模板',
  });
