import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { trafficControlRuleService } from '../../api/traffic-control-rule-service';
import {
  authorizedControllerPathOptionsLoader,
  buildDictOptionsLoader,
  buildEnumOptionsLoader,
  DEFAULT_CRUD_MODAL_WIDTH,
  roleOptionsLoader,
  tenantSiteDomainOptionsLoader,
  tenantOptionsLoader,
} from '../api-module';

const algorithmOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.TrafficControlRule$Algorithm',
);

const userTypeOptionsLoader = buildDictOptionsLoader(
  'com.levin.oak.base.entities.User.type',
);

const limitDimensionOptions = [
  { label: '规则', value: 'Rule' },
  { label: '租户', value: 'Tenant' },
  { label: '用户', value: 'User' },
  { label: 'IP', value: 'Ip' },
  { label: '路径', value: 'Path' },
  { label: '方法', value: 'Method' },
  { label: '请求头', value: 'Header' },
  { label: '请求参数', value: 'Param' },
];

const methodOptions = [
  { label: 'GET', value: 'GET' },
  { label: 'POST', value: 'POST' },
  { label: 'PUT', value: 'PUT' },
  { label: 'DELETE', value: 'DELETE' },
  { label: 'PATCH', value: 'PATCH' },
];

function transformRuleSubmit(values: Record<string, any>) {
  return { ...values };
}

export const trafficControlRulePageCrudConfig: CrudPageConfig = {
  apiBase: '/TrafficControlRule',
  apiService: trafficControlRuleService,
  defaultFormValues: {
    algorithm: 'FixedWindow',
    editable: true,
    enable: true,
    limitCount: 60,
    limitDimensionList: ['Rule'],
    orderCode: 100,
    rejectStatus: 429,
    windowSeconds: 60,
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForSaasUser: true,
    },
    {
      key: '__tenant',
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForSaasUser: true,
      width: 180,
    },
    {
      key: 'id',
      label: '规则ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'name',
      label: '规则名称',
      required: true,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'urlPathList',
      label: 'URL包含列表',
      fullRow: true,
      help: '可搜索授权控制器路径填入，也可手动配置通配符数组；支持*和?，例如 /api/order/*、/api/order/??/detail。',
      loadOptions: authorizedControllerPathOptionsLoader,
      remoteSearch: true,
      search: true,
      table: true,
      type: 'tags',
      width: 220,
    },
    {
      key: 'urlPathExcludeList',
      label: 'URL排除列表',
      fullRow: true,
      help: '可搜索授权控制器路径填入，也可手动配置通配符数组；命中排除列表时跳过当前限流规则。',
      loadOptions: authorizedControllerPathOptionsLoader,
      remoteSearch: true,
      type: 'tags',
    },
    {
      key: 'methodList',
      label: '请求方法',
      fullRow: true,
      help: '按数组配置，可配置多个请求方法。',
      options: methodOptions,
      search: true,
      table: true,
      type: 'tags',
      width: 140,
    },
    {
      key: 'domainList',
      label: '域名包含列表',
      fullRow: true,
      help: '从租户站点查询域名，支持手动补充*和?通配符；例如 *.example.com。',
      loadOptions: tenantSiteDomainOptionsLoader,
      remoteSearch: true,
      type: 'tags',
    },
    {
      key: 'regionList',
      label: '地区包含列表',
      fullRow: true,
      help: '按数组配置，通常根据IP判别地区，支持*和?。',
      type: 'tags',
    },
    {
      key: 'ipList',
      label: 'IP包含列表',
      fullRow: true,
      help: '按数组配置，支持*和?；例如 10.0.?.*。',
      search: true,
      table: true,
      type: 'tags',
      width: 180,
    },
    {
      key: 'ipExcludeList',
      label: 'IP排除列表',
      fullRow: true,
      help: '按数组配置，命中排除列表时跳过当前限流规则。',
      type: 'tags',
    },
    {
      key: 'userTypeList',
      label: '用户类型',
      fullRow: true,
      help: '按数组配置，支持*和?。',
      loadOptions: userTypeOptionsLoader,
      type: 'tags',
    },
    {
      key: 'userRoleList',
      label: '用户角色',
      fullRow: true,
      help: '按数组配置，支持*和?。',
      loadOptions: roleOptionsLoader,
      remoteSearch: true,
      type: 'tags',
    },
    {
      key: 'requestParamRuleList',
      label: '请求参数匹配数组',
      fullRow: true,
      help: 'JSON数组，每项配置name和value，名称和值支持*和?；示例：[{"name":"tenant*","value":"ma?ket-*"},{"name":"status","value":"*"}]。',
      placeholder:
        '[{"name":"tenant*","value":"ma?ket-*"},{"name":"status","value":"*"}]',
      type: 'json',
    },
    {
      key: 'headerRuleList',
      label: '请求头匹配数组',
      fullRow: true,
      help: 'JSON数组，每项配置name和value，名称和值支持*和?；示例：[{"name":"X-Tenant-*","value":"vip?"},{"name":"X-Client-App-Id","value":"*"}]。',
      placeholder:
        '[{"name":"X-Tenant-*","value":"vip?"},{"name":"X-Client-App-Id","value":"*"}]',
      type: 'json',
    },
    {
      key: 'limitDimensionList',
      label: '限流维度',
      fullRow: true,
      help: '系统始终包含规则ID；选择Header或Param时只使用已配置且命中的请求头或参数。',
      options: limitDimensionOptions,
      table: true,
      type: 'tags',
      width: 220,
    },
    {
      key: 'algorithm',
      label: '限流算法',
      loadOptions: algorithmOptionsLoader,
      required: true,
      search: true,
      table: true,
      type: 'select',
      width: 140,
    },
    {
      key: 'limitCount',
      label: '窗口请求数上限',
      required: true,
      table: true,
      type: 'number',
      valueType: 'number',
      width: 140,
    },
    {
      key: 'windowSeconds',
      label: '窗口秒数',
      required: true,
      table: true,
      type: 'number',
      valueType: 'number',
      width: 120,
    },
    {
      key: 'burstCount',
      label: '突发请求数',
      type: 'number',
      valueType: 'number',
    },
    {
      key: 'rejectStatus',
      label: '拒绝状态码',
      type: 'number',
      valueType: 'number',
    },
    {
      key: 'rejectMessage',
      label: '拒绝提示',
      fullRow: true,
      type: 'textarea',
    },
    {
      key: 'enable',
      label: '是否启用',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'orderCode',
      label: '排序代码',
      type: 'number',
      valueType: 'number',
    },
    {
      key: 'exInfo',
      label: '扩展信息',
      fullRow: true,
      type: 'json',
    },
    {
      key: 'remark',
      label: '备注',
      fullRow: true,
      type: 'textarea',
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '流量控制规则管理',
  transformSubmit: (values) => transformRuleSubmit(values),
};
