import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { trafficControlRuleService } from '../../api/traffic-control-rule-service';
import {
  authorizedControllerPathOptionsLoader,
  buildDictOptionsLoader,
  buildEnumOptionsLoader,
  DEFAULT_CRUD_MODAL_WIDTH,
  roleOptionsLoader,
  tenantOptionsLoader,
  tenantSiteDomainOptionsLoader,
} from '../api-module';
import { normalizeNameValueRuleList } from './traffic-control-match';

const algorithmOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.TrafficControlRule$Algorithm',
);

const userTypeOptionsLoader = buildDictOptionsLoader(
  'com.levin.oak.base.entities.User.type',
);

const limitDimensionOptions = [
  { label: '规则', value: 'Rule' },
  { label: '租户', value: 'Tenant' },
  { label: '用户', value: 'User' },
  { label: 'IP', value: 'Ip' },
  { label: '路径', value: 'Path' },
  { label: '方法', value: 'Method' },
  { label: '请求头', value: 'Header' },
  { label: '请求参数', value: 'Param' },
];

const methodOptions = [
  { label: 'GET', value: 'GET' },
  { label: 'POST', value: 'POST' },
  { label: 'PUT', value: 'PUT' },
  { label: 'DELETE', value: 'DELETE' },
  { label: 'PATCH', value: 'PATCH' },
];

const ANY_MATCH_HELP = '支持*和?匹配，本字段内任一命中。';

function transformRuleSubmit(values: Record<string, any>) {
  return {
    ...values,
    headerRuleList: normalizeNameValueRuleList(values.headerRuleList),
    requestParamRuleList: normalizeNameValueRuleList(
      values.requestParamRuleList,
    ),
  };
}

export const pageMeta = {
  name: 'TrafficControlRule',
  title: '流量控制规则管理',
  description: '维护流量控制规则。',
} as const;

export const trafficControlRulePageCrudConfig: CrudPageConfig = {
  apiBase: '/TrafficControlRule',
  apiService: trafficControlRuleService,
  defaultFormValues: {
    algorithm: 'FixedWindow',
    editable: true,
    enable: true,
    limitCount: 60,
    limitDimensionList: ['Rule'],
    orderCode: 100,
    rejectStatus: 429,
    windowSeconds: 60,
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: '__tenant',
      detail: false,
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForPlatformUser: true,
      width: 180,
    },
    {
      key: 'tenantId',
      label: '归属租户',
      layoutGroup: 'basic',
      layoutGroupTitle: '规则基本信息',
      layoutOrder: 1,
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForPlatformUser: true,
    },
    {
      key: 'id',
      label: '规则ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'containsName',
      label: '规则名称',
      form: false,
      search: true,
    },
    {
      key: 'name',
      label: '规则名称',
      layoutGroup: 'basic',
      layoutOrder: 20,
      required: true,
      table: true,
      width: 180,
    },
    {
      key: 'enable',
      label: '是否启用',
      layoutGroup: 'basic',
      layoutOrder: 30,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      layoutGroup: 'basic',
      layoutOrder: 40,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'urlPathList',
      label: 'URL包含列表',
      layoutGroup: 'conditions',
      layoutGroupTitle: '匹配条件',
      layoutOrder: 10,
      help: '可搜索授权控制器路径填入，也可手动配置通配符数组；支持*和?，例如 /api/order/*、/api/order/??/detail。本字段内任一命中。',
      layoutNewRow: true,
      loadOptions: authorizedControllerPathOptionsLoader,
      remoteSearch: true,
      search: true,
      span: 2,
      table: true,
      type: 'tags',
      width: 220,
    },
    {
      key: 'urlPathExcludeList',
      label: 'URL排除列表',
      layoutGroup: 'conditions',
      layoutOrder: 20,
      help: '可搜索授权控制器路径填入，也可手动配置通配符数组；支持*和?；命中排除列表时跳过当前限流规则。',
      loadOptions: authorizedControllerPathOptionsLoader,
      remoteSearch: true,
      span: 2,
      type: 'tags',
    },
    {
      key: 'methodList',
      label: '请求方法',
      layoutGroup: 'conditions',
      layoutOrder: 30,
      help: ANY_MATCH_HELP,
      options: methodOptions,
      search: true,
      span: 2,
      table: true,
      type: 'tags',
      width: 140,
    },
    {
      key: 'domainList',
      label: '域名包含列表',
      layoutGroup: 'conditions',
      layoutOrder: 40,
      help: '从租户站点查询域名，也可手动补充通配符；支持*和?，例如 *.example.com。本字段内任一命中。',
      loadOptions: tenantSiteDomainOptionsLoader,
      remoteSearch: true,
      span: 2,
      type: 'tags',
    },
    {
      key: 'regionList',
      label: '地区包含列表',
      layoutGroup: 'conditions',
      layoutOrder: 50,
      help: ANY_MATCH_HELP,
      span: 2,
      type: 'tags',
    },
    {
      key: 'ipList',
      label: 'IP包含列表',
      layoutGroup: 'conditions',
      layoutOrder: 60,
      help: '支持*和?匹配，例如 10.0.?.*；本字段内任一命中。',
      search: true,
      span: 2,
      table: true,
      type: 'tags',
      width: 180,
    },
    {
      key: 'ipExcludeList',
      label: 'IP排除列表',
      layoutGroup: 'conditions',
      layoutOrder: 70,
      help: '支持*和?匹配；命中排除列表时跳过当前限流规则。',
      span: 2,
      type: 'tags',
    },
    {
      key: 'userTypeList',
      label: '用户类型',
      layoutGroup: 'conditions',
      layoutOrder: 80,
      help: ANY_MATCH_HELP,
      loadOptions: userTypeOptionsLoader,
      span: 2,
      type: 'tags',
    },
    {
      key: 'userRoleList',
      label: '用户角色',
      layoutGroup: 'conditions',
      layoutOrder: 90,
      help: ANY_MATCH_HELP,
      loadOptions: roleOptionsLoader,
      remoteSearch: true,
      span: 2,
      type: 'tags',
    },
    {
      key: 'requestParamRuleList',
      label: '请求参数匹配列表',
      layoutGroup: 'conditions',
      layoutOrder: 100,
      help: '每项使用未编码的name=value，必须且只能包含一个等号；名称和值支持*和?。示例：tenant*=ma?ket-*、status=*。',
      placeholder: '例如 tenant*=ma?ket-*',
      span: 2,
      type: 'tags',
    },
    {
      key: 'headerRuleList',
      label: '请求头匹配列表',
      layoutGroup: 'conditions',
      layoutOrder: 110,
      help: '每项使用未编码的name=value，必须且只能包含一个等号；名称和值支持*和?。示例：X-Tenant-*=vip?、X-Client-App-Id=*。',
      placeholder: '例如 X-Tenant-*=vip?',
      span: 2,
      type: 'tags',
    },
    {
      key: 'limitDimensionList',
      label: '限流维度',
      layoutGroup: 'conditions',
      layoutOrder: 120,
      help: '系统始终包含规则ID；选择Header或Param时只使用已配置且命中的请求头或参数。本字段内任一命中。',
      options: limitDimensionOptions,
      span: 2,
      table: true,
      type: 'tags',
      width: 220,
    },
    {
      key: 'algorithm',
      label: '限流算法',
      layoutGroup: 'limit',
      layoutGroupTitle: '限流策略',
      layoutOrder: 10,
      loadOptions: algorithmOptionsLoader,
      required: true,
      search: true,
      table: true,
      type: 'select',
      width: 140,
    },
    {
      key: 'limitCount',
      label: '窗口请求数上限',
      layoutGroup: 'limit',
      layoutOrder: 20,
      required: true,
      table: true,
      type: 'number',
      valueType: 'number',
      width: 140,
    },
    {
      key: 'windowSeconds',
      label: '窗口秒数',
      layoutGroup: 'limit',
      layoutOrder: 30,
      required: true,
      table: true,
      type: 'number',
      valueType: 'number',
      width: 120,
    },
    {
      key: 'burstCount',
      label: '突发请求数',
      layoutGroup: 'limit',
      layoutOrder: 40,
      type: 'number',
      valueType: 'number',
    },
    {
      key: 'rejectStatus',
      label: '拒绝状态码',
      layoutGroup: 'limit',
      layoutOrder: 50,
      type: 'number',
      valueType: 'number',
    },
    {
      key: 'orderCode',
      label: '排序代码',
      layoutGroup: 'limit',
      layoutOrder: 60,
      type: 'number',
      valueType: 'number',
    },
    {
      key: 'rejectMessage',
      label: '拒绝提示',
      layoutGroup: 'limit',
      layoutOrder: 70,
      fullRow: true,
      layoutNewRow: true,
      type: 'textarea',
    },
    {
      key: 'exInfo',
      label: '扩展信息',
      layoutGroup: 'limit',
      layoutOrder: 80,
      type: 'json',
    },
    {
      key: 'remark',
      label: '备注',
      fullRow: true,
      type: 'textarea',
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  formMaxColumns: 4,
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '流量控制规则管理',
  transformSubmit: (values) => transformRuleSubmit(values),
};
