import type { CrudPageConfig } from '../../shared/types';

import { settingService } from '#/api/com_levin_oak_base/setting';

import { buildApiMethodPermissions } from '../../shared/crud-permissions';
import {
  DEFAULT_CRUD_MODAL_WIDTH,
  buildEnumOptionsLoader,
  tenantOptionsLoader,
} from '../api-module';

const settingValueTypeOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.Setting$ValueType',
);

export const settingPageCrudConfig: CrudPageConfig = {
  apiBase: '/Setting',
  createPermission: buildApiMethodPermissions(settingService, 'create'),
  defaultFormValues: {
    editable: true,
    enable: true,
    nullable: true,
    orderCode: 100,
    valueType: 'Text',
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  deletePermission: buildApiMethodPermissions(settingService, 'delete'),
  editPermission: buildApiMethodPermissions(settingService, 'update'),
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForSaasUser: true,
    },
    {
      key: '__tenant',
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForSaasUser: true,
      width: 180,
    },
    {
      key: 'id',
      label: '设置ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    { key: 'containsName', label: '名称', form: false, search: true },
    { key: 'code', label: '编码', form: false, search: true },
    { key: 'categoryName', label: '分类名称', form: false, search: true },
    { key: 'containsGroupName', label: '分组名称', form: false, search: true },
    { key: 'endsWithDomain', label: '域名', form: false, search: true },
    {
      key: 'inValueType',
      label: '值类型',
      form: false,
      loadOptions: settingValueTypeOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'gteCreateTime',
      label: '创建时间开始',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'lteCreateTime',
      label: '创建时间结束',
      form: false,
      search: true,
      type: 'datetime',
    },
    { key: 'name', label: '名称', required: true, table: true, width: 180 },
    { key: 'code', label: '编码', required: true, table: true, width: 180 },
    { key: 'categoryName', label: '分类名称', table: true, width: 140 },
    { key: 'groupName', label: '分组名称', table: true, width: 140 },
    { key: 'domain', label: '域名', table: true, width: 180 },
    { key: 'icon', label: '图标', type: 'image' },
    {
      key: 'valueType',
      label: '值类型',
      loadOptions: settingValueTypeOptionsLoader,
      table: true,
      type: 'select',
      width: 120,
    },
    { key: 'editor', label: '值编辑器', fullRow: true, type: 'textarea' },
    { key: 'valueContent', label: '值', fullRow: true, type: 'textarea' },
    {
      key: 'nullable',
      label: '值是否可空',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 120,
    },
    {
      key: 'inputPlaceholder',
      label: '输入占位提示',
      fullRow: true,
      type: 'textarea',
    },
    { key: 'pinyinName', label: '拼音名', table: true, width: 160 },
    { key: 'orderCode', label: '排序代码', type: 'number' },
    {
      key: 'enable',
      label: '是否启用',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    { key: 'remark', label: '备注', type: 'textarea' },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  queryPermission: buildApiMethodPermissions(settingService, 'list'),
  title: '系统设置管理',
};
