import type { CrudPageConfig } from '../../shared/types';

import { DEFAULT_CRUD_MODAL_WIDTH, tenantOptionsLoader } from '../api-module';

export const tenantAppPageCrudConfig: CrudPageConfig = {
  apiBase: '/TenantApp',
  defaultFormValues: {
    editable: true,
    enable: true,
    modules: [],
    orderCode: 100,
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForSaasUser: true,
    },
    {
      key: '__tenant',
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForSaasUser: true,
      width: 180,
    },
    {
      key: 'id',
      label: '应用ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    { key: 'containsName', label: '名称', form: false, search: true },
    { key: 'name', label: '名称', required: true, table: true, width: 180 },
    {
      key: 'code',
      label: '应用编码',
      required: true,
      search: true,
      table: true,
      width: 160,
    },
    {
      key: 'gteExpiredTime',
      label: '到期时间开始',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'lteExpiredTime',
      label: '到期时间结束',
      form: false,
      search: true,
      type: 'datetime',
    },
    { key: 'logo', label: '应用Logo', table: true, type: 'image', width: 120 },
    { key: 'entryUrl', label: '应用入口', table: true, width: 220 },
    { key: 'infoUrl', label: '应用说明页', table: true, width: 220 },
    { key: 'modules', label: '模块列表', fullRow: true, type: 'tags' },
    { key: 'appSecret', label: '应用密钥', type: 'password' },
    {
      key: 'salePrice',
      label: '销售价格',
      table: true,
      type: 'number',
      width: 120,
    },
    {
      key: 'purchasePrice',
      label: '采购价格',
      table: true,
      type: 'number',
      width: 120,
    },
    {
      key: 'orderNo',
      label: '订单编号',
      search: true,
      table: true,
      width: 160,
    },
    {
      key: 'expiredTime',
      label: '到期时间',
      table: true,
      type: 'datetime',
      width: 180,
    },
    { key: 'exInfo', label: '扩展信息', fullRow: true, type: 'json' },
    { key: 'pinyinName', label: '拼音名', table: true, width: 160 },
    {
      key: 'enable',
      label: '是否启用',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    { key: 'remark', label: '备注', type: 'textarea' },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '租户应用管理',
};
