import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { addressService } from '../../api/address-service';
import {
  buildEnumOptionsLoader,
  DEFAULT_CRUD_MODAL_WIDTH,
  nationCodeOptionsLoader,
  tenantOptionsLoader,
} from '../api-module';

const addressCategoryOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.Address$Category',
);

export const pageMeta = {
  name: 'Address',
  title: '地址管理',
  description: '维护收寄地址信息。',
} as const;

export const addressPageCrudConfig: CrudPageConfig = {
  apiBase: '/Address',
  apiService: addressService,
  defaultFormValues: {
    category: 'ReceiveAndSend',
    editable: true,
    enable: true,
    isDefault: false,
    orderCode: 100,
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      layoutGroup: 'basic',
      layoutGroupTitle: '地址信息',
      layoutOrder: 5,
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForPlatformUser: true,
    },
    {
      key: '__tenant',
      detail: false,
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForPlatformUser: true,
      width: 180,
    },
    {
      key: 'id',
      label: '地址ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    { key: 'containsName', label: '收寄件人姓名', form: false, search: true },
    {
      key: 'containsTelephone',
      label: '收寄件人手机号',
      form: false,
      search: true,
    },
    {
      key: 'inCategory',
      label: '地址类别',
      form: false,
      loadOptions: addressCategoryOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'nationCode',
      label: '国家编码',
      layoutGroup: 'basic',
      layoutOrder: 10,
      loadOptions: nationCodeOptionsLoader,
      search: true,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'districtCode',
      label: '区域编码',
      layoutGroup: 'basic',
      layoutOrder: 20,
      areaCascader: {
        selectableLevels: ['district'],
        valueKey: 'districtCode',
      },
      required: true,
      search: true,
      table: true,
      type: 'area-cascader',
      width: 120,
    },
    { key: 'containsPostalCode', label: '邮编', form: false, search: true },
    {
      key: 'postalCode',
      label: '邮编',
      layoutGroup: 'basic',
      layoutOrder: 30,
      table: true,
      width: 120,
    },
    {
      key: 'gteCreateTime',
      label: '创建时间开始',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'lteCreateTime',
      label: '创建时间结束',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'name',
      label: '收寄件人姓名',
      layoutGroup: 'basic',
      layoutOrder: 40,
      table: true,
      width: 140,
    },
    {
      key: 'telephone',
      label: '收寄件人手机号',
      layoutGroup: 'basic',
      layoutOrder: 50,
      table: true,
      width: 140,
    },
    {
      key: 'category',
      label: '地址类别',
      layoutGroup: 'basic',
      layoutOrder: 60,
      loadOptions: addressCategoryOptionsLoader,
      table: true,
      type: 'select',
      width: 140,
    },
    {
      key: 'bizType',
      label: '业务类型',
      layoutGroup: 'basic',
      layoutOrder: 70,
      required: true,
    },
    {
      key: 'address',
      label: '详细地址',
      fullRow: true,
      layoutGroup: 'basic',
      layoutOrder: 80,
      required: true,
      type: 'textarea',
    },
    {
      key: 'isDefault',
      label: '是否默认地址',
      layoutGroup: 'business',
      layoutGroupTitle: '状态与排序',
      layoutOrder: 10,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 120,
    },
    {
      key: 'enable',
      label: '是否启用',
      layoutGroup: 'business',
      layoutOrder: 20,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      layoutGroup: 'business',
      layoutOrder: 30,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'orderCode',
      label: '排序代码',
      layoutGroup: 'business',
      layoutOrder: 40,
      type: 'number',
    },
    {
      key: 'remark',
      label: '备注',
      fullRow: true,
      layoutGroup: 'business',
      layoutOrder: 50,
      type: 'textarea',
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '地址管理',
};
