import type { Preferences } from './types';

const defaultPreferences: Preferences = {
  app: {
    accessMode: 'frontend',
    authPageLayout: 'panel-right',
    checkUpdatesInterval: 1,
    colorGrayMode: false,
    colorWeakMode: false,
    compact: false,
    contentCompact: 'wide',
    contentCompactWidth: 1200,
    contentPadding: 0,
    contentMarginBottom: 0,
    contentMarginLeft: 0,
    contentMarginRight: 0,
    contentMarginTop: 0,
    contentRadiusTopLeft: 0,
    contentRadiusTopRight: 0,
    contentRadiusBottomRight: 0,
    contentRadiusBottomLeft: 0,
    contentBorderTopWidth: 0,
    contentBorderRightWidth: 0,
    contentBorderBottomWidth: 0,
    contentBorderLeftWidth: 0,
    defaultAvatar:
      'https://unpkg.com/@vbenjs/static-source@0.1.7/source/avatar-v1.webp',
    defaultHomePath: '/analytics',
    dynamicTitle: true,
    enableCheckUpdates: true,
    enablePreferences: true,
    enableRefreshToken: false,
    enableStickyPreferencesNavigationBar: true,
    isMobile: false,
    layout: 'sidebar-nav',
    locale: 'zh-CN',
    loginExpiredMode: 'page',
    name: 'Vben Admin',
    preferencesButtonPosition: 'auto',
    watermark: false,
    watermarkColor: 'gray',
    watermarkColorCustom: false,
    watermarkTransparency: 85,
    watermarkContent: '',
    zIndex: 200,
  },
  breadcrumb: {
    enable: true,
    hideOnlyOne: false,
    showHome: false,
    showIcon: true,
    styleType: 'normal',
  },
  copyright: {
    companyName: '',
    companySiteLink: '',
    date: '',
    enable: true,
    icp: '',
    icpLink: '',
    settingShow: true,
  },
  footer: {
    backgroundColor: '#f2f4f7',
    backgroundColorCustom: false,
    backgroundTransparency: 0,
    enable: false,
    fixed: false,
    height: 32,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    radiusTopLeft: 0,
    radiusTopRight: 0,
    radiusBottomRight: 0,
    radiusBottomLeft: 0,
  },
  header: {
    enable: true,
    height: 50,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    radiusTopLeft: 0,
    radiusTopRight: 0,
    radiusBottomRight: 0,
    radiusBottomLeft: 0,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    hidden: false,
    menuAlign: 'start',
    mode: 'fixed',
  },

  logo: {
    enable: true,
    fit: 'contain',
    source: 'https://unpkg.com/@vbenjs/static-source@0.1.7/source/logo-v1.webp',
  },
  navigation: {
    accordion: true,
    split: true,
    styleType: 'rounded',
  },
  shortcutKeys: {
    enable: true,
    globalLockScreen: true,
    globalLogout: true,
    globalPreferences: true,
    globalSearch: true,
  },
  sidebar: {
    autoActivateChild: false,
    collapsed: false,
    collapsedButton: true,
    collapsedShowTitle: false,
    collapseWidth: 60,
    enable: true,
    expandOnHover: true,
    extraCollapse: false,
    extraCollapsedWidth: 60,
    fixedButton: true,
    hidden: false,
    mixedWidth: 80,
    mixedMenuGap: 6,
    menuItemGap: 4,
    width: 224,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    radiusTopLeft: 0,
    radiusTopRight: 0,
    radiusBottomRight: 0,
    radiusBottomLeft: 0,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
  },
  tabbar: {
    backgroundColor: 'hsl(0 0% 100%)',
    backgroundColorCustom: false,
    backgroundTransparency: 0,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    radiusTopLeft: 0,
    radiusTopRight: 0,
    radiusBottomRight: 0,
    radiusBottomLeft: 0,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 1,
    borderLeftWidth: 0,
    draggable: true,
    enable: true,
    height: 38,
    keepAlive: true,
    maxCount: 0,
    middleClickToClose: false,
    persist: true,
    showIcon: true,
    showMaximize: true,
    showMore: true,
    showRefresh: true,
    styleType: 'chrome',
    visitHistory: true,
    wheelable: true,
  },
  theme: {
    baseBackgroundColor: 'hsl(210 40% 96%)',
    baseBackgroundColorCustom: false,
    baseBackgroundTransparency: 0,
    contentBackgroundColor: 'hsl(0 0% 100%)',
    contentBackgroundColorCustom: false,
    contentBackgroundTransparency: 0,
    builtinType: 'default',
    colorDestructive: 'hsl(348 100% 61%)',
    colorPrimary: 'hsl(212 100% 45%)',
    colorSuccess: 'hsl(144 57% 58%)',
    colorWarning: 'hsl(42 84% 61%)',
    mode: 'dark',
    radius: '0.5',
    fontSize: 16,
    fontFamily: '',
    headingFontSizeScale: 1.25,
    sidebarMenuFontSizeScale: 0.875,
    headerMenuFontSizeScale: 0.875,
    tabbarFontSizeScale: 0.875,
    breadcrumbFontSizeScale: 0.875,
    footerFontSizeScale: 0.875,
    semiDarkHeader: false,
    semiDarkHeaderColor: 'hsl(222 10% 12%)',
    semiDarkHeaderColorTransparency: 0,
    headerMenuThemeColor: 'hsl(210 40% 96%)',
    headerMenuThemeColorCustom: false,
    headerMenuBackgroundColor: 'hsl(222 10% 12%)',
    headerMenuBackgroundColorCustom: false,
    headerMenuBackgroundColorTransparency: 0,
    semiDarkSidebar: false,
    semiDarkSidebarColor: 'hsl(222 10% 12%)',
    semiDarkSidebarColorTransparency: 0,
    semiDarkSidebarSub: false,
    sidebarMenuBackgroundColor: 'hsl(222 10% 12%)',
    sidebarMenuBackgroundColorCustom: false,
    sidebarMenuBackgroundColorTransparency: 0,
  },
  transition: {
    enable: true,
    loading: true,
    name: 'fade-slide',
    progress: true,
  },
  widget: {
    fullscreen: true,
    globalSearch: true,
    languageToggle: true,
    lockScreen: true,
    notification: true,
    refresh: true,
    sidebarToggle: true,
    themeToggle: true,
    timezone: true,
  },
};

export { defaultPreferences };
