import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { fileResService } from '../../api/file-res-service';
import {
  buildEnumOptionsLoader,
  DEFAULT_CRUD_MODAL_WIDTH,
  FILE_STORAGE_MULTI_UPLOAD_PATH,
  FILE_STORAGE_SINGLE_UPLOAD_PATH,
  tenantOptionsLoader,
  userOptionsLoader,
} from '../api-module';

const fileResTypeOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.FileRes$Type',
);
const confidentialLevelOptionsLoader = buildEnumOptionsLoader(
  'com.levin.commons.rbac.ConfidentialLevel',
);

export const pageMeta = {
  name: 'FileRes',
  title: '文件资源库',
  description: '维护文件资源库。',
} as const;

export const fileResPageCrudConfig: CrudPageConfig = {
  apiBase: '/FileRes',
  apiService: fileResService,
  defaultFormValues: {
    editable: true,
    enable: true,
    orderCode: 100,
    paths: [],
    tagList: [],
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      layoutGroup: 'ownership',
      layoutGroupTitle: '归属信息',
      layoutOrder: 10,
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForPlatformUser: true,
    },
    {
      key: '__tenant',
      detail: false,
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForPlatformUser: true,
      width: 180,
    },
    {
      key: 'orgId',
      label: '所属组织',
      layoutGroup: 'ownership',
      layoutOrder: 20,
      type: 'org-tree-select',
    },
    {
      key: 'ownerId',
      label: '所属用户',
      layoutGroup: 'ownership',
      layoutOrder: 30,
      loadOptions: userOptionsLoader,
      remoteSearch: true,
      type: 'select',
    },
    {
      key: 'id',
      label: '文件ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'name',
      label: '文件名称',
      layoutGroup: 'basic',
      layoutGroupTitle: '文件信息',
      layoutOrder: 10,
      required: true,
      search: true,
      table: true,
      width: 220,
    },
    {
      key: 'bizType',
      label: '业务类型',
      layoutGroup: 'basic',
      layoutOrder: 20,
      required: true,
      table: true,
      width: 160,
    },
    {
      key: 'type',
      label: '文件类型',
      layoutGroup: 'basic',
      layoutOrder: 30,
      loadOptions: fileResTypeOptionsLoader,
      required: true,
      search: true,
      table: true,
      type: 'select',
      width: 140,
    },
    {
      key: 'confidentialLevel',
      label: '机密等级',
      layoutGroup: 'basic',
      layoutOrder: 35,
      loadOptions: confidentialLevelOptionsLoader,
      type: 'select',
      valueType: 'number',
    },
    {
      key: 'category',
      label: '类别',
      layoutGroup: 'basic',
      layoutOrder: 40,
      search: true,
      table: true,
      width: 140,
    },
    {
      key: 'mimeType',
      label: 'Mime类型',
      layoutGroup: 'basic',
      layoutOrder: 50,
      table: true,
      width: 160,
    },
    {
      key: 'bizObjId',
      label: '业务对象ID',
      layoutGroup: 'basic',
      layoutOrder: 60,
      table: true,
      width: 180,
    },
    {
      key: 'paths',
      label: '文件路径',
      layoutGroup: 'basic',
      layoutOrder: 70,
      multiple: true,
      type: 'file',
      uploadPath: FILE_STORAGE_MULTI_UPLOAD_PATH,
    },
    {
      key: 'tagList',
      label: '标签列表',
      layoutGroup: 'basic',
      layoutOrder: 90,
      type: 'tags',
    },
    {
      key: 'publishable',
      label: '公网发布',
      layoutGroup: 'business',
      layoutGroupTitle: '共享与状态',
      layoutOrder: 10,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'deleted',
      label: '已删除',
      layoutGroup: 'business',
      layoutOrder: 20,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'tenantShared',
      label: '租户共享',
      layoutGroup: 'business',
      layoutOrder: 30,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'orgShared',
      label: '组织共享',
      layoutGroup: 'business',
      layoutOrder: 40,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'enable',
      label: '是否启用',
      layoutGroup: 'business',
      layoutOrder: 50,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      layoutGroup: 'business',
      layoutOrder: 60,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'exInfo',
      label: '扩展信息',
      type: 'json',
    },
    {
      key: 'coverUrl',
      label: '封面图',
      layoutGroup: 'basic',
      layoutOrder: 80,
      table: true,
      type: 'image',
      uploadPath: FILE_STORAGE_SINGLE_UPLOAD_PATH,
      width: 120,
    },
    {
      key: 'remark',
      label: '备注',
      fullRow: true,
      type: 'textarea',
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '文件资源库',
};
