import type { CrudPageConfig } from '../../shared/types';

import {
  DEFAULT_CRUD_MODAL_WIDTH,
  buildEnumOptionsLoader,
  tenantOptionsLoader,
} from '../api-module';

const executionContentTypeOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.ScheduledTask$ExecutionContentType',
);

export const scheduledTaskPageCrudConfig: CrudPageConfig = {
  apiBase: '/ScheduledTask',
  defaultFormValues: {
    editable: true,
    enable: true,
    executionCount: 0,
    orderCode: 100,
    parallelExecution: false,
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForSaasUser: true,
    },
    {
      key: '__tenant',
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForSaasUser: true,
      width: 180,
    },
    {
      key: 'id',
      label: '任务ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'name',
      label: '名称',
      required: true,
      search: true,
      table: true,
      width: 180,
    },
    { key: 'timeZone', label: '时区', table: true, width: 140 },
    {
      key: 'category',
      label: '任务分类',
      search: true,
      table: true,
      width: 140,
    },
    { key: 'containsGroupName', label: '任务组', form: false, search: true },
    { key: 'groupName', label: '任务组', table: true, width: 160 },
    {
      key: 'cron',
      label: '调度表达式',
      required: true,
      table: true,
      width: 180,
    },
    {
      key: 'inExecutionContentType',
      label: '执行内容类型',
      form: false,
      loadOptions: executionContentTypeOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'executionContentType',
      label: '执行内容类型',
      loadOptions: executionContentTypeOptionsLoader,
      table: true,
      type: 'select',
      width: 140,
    },
    {
      key: 'executionContent',
      label: '执行内容',
      fullRow: true,
      type: 'textarea',
    },
    {
      key: 'parallelExecution',
      label: '允许并发执行',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 120,
    },
    {
      key: 'executionCount',
      label: '执行累计次数',
      table: true,
      type: 'number',
      width: 120,
    },
    {
      key: 'gteCreateTime',
      label: '创建时间开始',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'lteCreateTime',
      label: '创建时间结束',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'lastScheduledExecutionTime',
      label: '最后调度时间',
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastActualExecutionTime',
      label: '最后实际执行时间',
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastCompletionTime',
      label: '最后完成时间',
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'nextExecutionTime',
      label: '下一次执行时间',
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'enable',
      label: '是否启用',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    { key: 'remark', label: '备注', type: 'textarea' },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '定时任务管理',
};
