import type { CrudPageConfig } from '../../shared/types';

import {
  buildEnumOptionsLoader,
  DEFAULT_CRUD_MODAL_WIDTH,
  roleOptionsLoader,
  tenantOptionsLoader,
} from '../api-module';

const interceptTypeOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.UrlExAcl$InterceptType',
);

export const urlExAclPageCrudConfig: CrudPageConfig = {
  apiBase: '/UrlExAcl',
  defaultFormValues: {
    editable: true,
    enable: true,
    orderCode: 100,
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForSaasUser: true,
    },
    {
      key: '__tenant',
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForSaasUser: true,
      width: 180,
    },
    {
      key: 'id',
      label: 'ACL ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'name',
      label: '名称',
      required: true,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'pinyinName',
      label: '拼音名',
      table: true,
      width: 160,
    },
    {
      key: 'interceptType',
      label: '拦截类型',
      loadOptions: interceptTypeOptionsLoader,
      search: true,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'interceptor',
      label: '拦截器Bean名称',
      search: true,
      table: true,
      width: 220,
    },
    {
      key: 'enable',
      label: '是否启用',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'urlPathList',
      label: 'URL包含列表',
      fullRow: true,
      type: 'tags',
    },
    {
      key: 'urlPathExcludeList',
      label: 'URL排除列表',
      fullRow: true,
      type: 'tags',
    },
    {
      key: 'methodList',
      label: '请求方法包含列表',
      fullRow: true,
      type: 'tags',
    },
    {
      key: 'domainList',
      label: '域名包含列表',
      fullRow: true,
      type: 'tags',
    },
    {
      key: 'regionList',
      label: '地区包含列表',
      fullRow: true,
      type: 'tags',
    },
    {
      key: 'ipList',
      label: 'IP地址包含列表',
      fullRow: true,
      type: 'tags',
    },
    {
      key: 'ipExcludeList',
      label: 'IP地址排除列表',
      fullRow: true,
      type: 'tags',
    },
    {
      key: 'osList',
      label: '操作系统包含列表',
      fullRow: true,
      type: 'tags',
    },
    {
      key: 'userTypeList',
      label: '用户类型包含列表',
      fullRow: true,
      type: 'tags',
    },
    {
      key: 'userRoleList',
      label: '用户角色包含列表',
      fullRow: true,
      loadOptions: roleOptionsLoader,
      multiple: true,
      remoteSearch: true,
      type: 'role-select',
    },
    {
      key: 'exInfo',
      label: '扩展信息',
      fullRow: true,
      type: 'json',
    },
    {
      key: 'remark',
      label: '备注',
      fullRow: true,
      type: 'textarea',
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  permissionResourceName: 'Url扩展拦截',
  permissionTypePrefix: '专家数据-',
  title: 'URL访问控制管理',
};
