import type { CrudPageConfig } from '../../shared/types';

import {
  DEFAULT_CRUD_MODAL_WIDTH,
  buildEnumOptionsLoader,
  roleOptionsLoader,
} from '../api-module';

const permissionCategoryOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.Permission$Category',
);
const permissionActionTypeOptionsLoader = buildEnumOptionsLoader(
  'com.levin.commons.rbac.ActionType',
);
const confidentialLevelOptionsLoader = buildEnumOptionsLoader(
  'com.levin.commons.rbac.ConfidentialLevel',
);

export const permissionPageCrudConfig: CrudPageConfig = {
  apiBase: '/Permission',
  allowRetrieve: true,
  defaultFormValues: {
    editable: true,
    enable: true,
    ignored: false,
    isAndMode: false,
    onlyRequireAuthenticated: false,
    orderCode: 100,
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  permissionTypePrefix: '平台数据-',
  fields: [
    {
      key: 'id',
      label: '权限ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    { key: 'icon', label: '图标', type: 'image' },
    {
      key: 'inCategory',
      label: '类别',
      form: false,
      loadOptions: permissionCategoryOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'category',
      label: '类别',
      loadOptions: permissionCategoryOptionsLoader,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'domain',
      label: '资源域',
      required: true,
      search: true,
      table: true,
      width: 140,
    },
    {
      key: 'type',
      label: '资源类型',
      required: true,
      search: true,
      table: true,
      width: 140,
    },
    { key: 'res', label: '资源标识', search: true, table: true, width: 160 },
    { key: 'action', label: '操作', search: true, table: true, width: 120 },
    {
      key: 'actionTypes',
      label: '操作类型',
      fullRow: true,
      loadOptions: permissionActionTypeOptionsLoader,
      multiple: true,
      type: 'select',
    },
    {
      key: 'ignored',
      label: '是否忽略',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'onlyRequireAuthenticated',
      label: '仅要求认证',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 120,
    },
    {
      key: 'isAndMode',
      label: '匹配模式',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'verifyExpression',
      label: '验证表达式',
      fullRow: true,
      type: 'textarea',
    },
    {
      key: 'confidentialLevel',
      label: '数据保密级别',
      loadOptions: confidentialLevelOptionsLoader,
      type: 'select',
      valueType: 'number',
    },
    {
      key: 'anyRoles',
      label: '任意角色',
      fullRow: true,
      loadOptions: roleOptionsLoader,
      multiple: true,
      remoteSearch: true,
      type: 'role-select',
    },
    { key: 'anyUserTypes', label: '任意用户类型', fullRow: true, type: 'tags' },
    {
      key: 'enable',
      label: '是否启用',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    { key: 'remark', label: '备注', type: 'textarea' },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '权限管理',
};
