import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { fundExchangeRuleService } from '../../api/fund-exchange-rule-service';
import {
  DEFAULT_CRUD_MODAL_WIDTH,
  buildDictOptionsLoader,
  buildEnumOptionsLoader,
  tenantOptionsLoader,
} from '../api-module';

const currencyTypeOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.enums.CurrencyType',
);
const currencyCodeOptionsLoader = buildDictOptionsLoader('CurrencyCode');

export const pageMeta = {
  name: 'FundExchangeRule',
  title: '资金兑换规则管理',
  description: '维护资金兑换规则。',
} as const;

export const fundExchangeRulePageCrudConfig: CrudPageConfig = {
  apiBase: '/FundExchangeRule',
  apiService: fundExchangeRuleService,
  defaultFormValues: {
    editable: true,
    enable: true,
    orderCode: 100,
    sourceCurrencyOnlyFromRecharge: false,
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      layoutGroup: 'ownership',
      layoutGroupTitle: '归属信息',
      layoutOrder: 10,
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForPlatformUser: true,
    },
    {
      key: '__tenant',
      detail: false,
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForPlatformUser: true,
      width: 180,
    },
    {
      key: 'id',
      label: '规则ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'containsName',
      label: '名称',
      form: false,
      search: true,
    },
    {
      key: 'name',
      label: '名称',
      layoutGroup: 'basic',
      layoutGroupTitle: '规则信息',
      layoutOrder: 10,
      required: true,
      table: true,
      width: 160,
    },
    {
      key: 'category',
      label: '规则类别',
      layoutGroup: 'basic',
      layoutOrder: 20,
      search: true,
      table: true,
      width: 140,
    },
    {
      key: 'gteExpiredTime',
      label: '有效期开始',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'lteExpiredTime',
      label: '有效期结束',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'expiredTime',
      label: '有效期',
      layoutGroup: 'basic',
      layoutOrder: 30,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'sourceCurrencyOnlyFromRecharge',
      label: '仅支持外部充值来源',
      layoutGroup: 'basic',
      layoutOrder: 40,
      required: true,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 140,
    },
    {
      key: 'inSourceCurrencyType',
      label: '原货币类型',
      form: false,
      loadOptions: currencyTypeOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'sourceCurrencyType',
      label: '原货币类型',
      layoutGroup: 'business',
      layoutGroupTitle: '兑换信息',
      layoutOrder: 10,
      loadOptions: currencyTypeOptionsLoader,
      required: true,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'sourceCurrencyCode',
      label: '原货币代码',
      layoutGroup: 'business',
      layoutOrder: 20,
      loadOptions: currencyCodeOptionsLoader,
      required: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'sourceCurrencyAmount',
      label: '原货币数量',
      layoutGroup: 'business',
      layoutOrder: 30,
      required: true,
      table: true,
      type: 'number',
      width: 120,
    },
    {
      key: 'inTargetCurrencyType',
      label: '目标货币类型',
      form: false,
      loadOptions: currencyTypeOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'targetCurrencyType',
      label: '目标货币类型',
      layoutGroup: 'business',
      layoutOrder: 40,
      loadOptions: currencyTypeOptionsLoader,
      required: true,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'targetCurrencyCode',
      label: '目标货币代码',
      layoutGroup: 'business',
      layoutOrder: 50,
      loadOptions: currencyCodeOptionsLoader,
      required: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'targetCurrencyAmount',
      label: '目标货币数量',
      layoutGroup: 'business',
      layoutOrder: 60,
      required: true,
      table: true,
      type: 'number',
      width: 120,
    },
    { key: 'targetCurrencyDuration', label: '目标有效时长', layoutGroup: 'business', layoutOrder: 70, type: 'number' },
    {
      key: 'enable',
      label: '是否启用',
      layoutGroup: 'business',
      layoutOrder: 80,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      layoutGroup: 'business',
      layoutOrder: 90,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'deleted',
      label: '是否已删除',
      layoutGroup: 'business',
      layoutOrder: 100,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    { key: 'remark', label: '备注', fullRow: true, layoutGroup: 'remark', layoutGroupTitle: '备注信息', layoutOrder: 10, type: 'textarea' },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '资金兑换规则管理',
};
