import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { orgService } from '../../api/org-service';
import {
  areaOptionsLoader,
  confidentialLevelOptionsLoader,
  legalSubjectOptionsLoader,
  orgCategoryOptionsLoader,
  orgLevelOptionsLoader,
  orgStateOptionsLoader,
  orgTypeOptionsLoader,
  tenantOptionsLoader,
} from '../api-module';

export const orgPageCrudConfig: CrudPageConfig = {
  apiBase: '/Org',
  apiService: orgService,
  allowRetrieve: true,
  defaultFormValues: {
    editable: true,
    enable: true,
    orderCode: 100,
    state: 'Normal',
    type: 'Department',
  },
  defaultQuery: {
    loadArea: true,
    loadParent: true,
    pageIndex: 1,
    pageSize: 10,
  },
  complexGroups: [
    {
      key: 'bank-account',
      title: '银行账号',
      submitKey: 'bankAccount',
      fieldMappings: {
        bankAccountName: 'bankAccountName',
        bankAccountNo: 'bankAccount',
        bankBranchCode: 'bankBranchCode',
        bankName: 'bankName',
      },
    },
  ],
  description:
    '组织保留自身的联系人、地址和银行资料；仅外部法律主体组织关联外部主体，内部部门或分支使用组织自身资料。',
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForPlatformUser: true,
    },
    {
      key: '__tenant',
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForPlatformUser: true,
      width: 180,
    },
    {
      key: 'id',
      label: '组织ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    { key: 'containsName', label: '机构名称', form: false, search: true },
    { key: 'name', label: '机构名称', required: true, table: true, width: 150 },
    { key: 'containsCode', label: '机构编码', form: false, search: true },
    { key: 'code', label: '机构编码', table: true, width: 140 },
    {
      key: 'parentId',
      label: '上级机构',
      search: true,
      type: 'org-tree-select',
    },
    {
      key: 'parent.name',
      label: '上级机构',
      form: false,
      table: true,
      width: 150,
    },
    {
      key: 'inType',
      label: '机构类型',
      form: false,
      loadOptions: orgTypeOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'type',
      label: '机构类型',
      loadOptions: orgTypeOptionsLoader,
      table: true,
      type: 'select',
      width: 130,
    },
    {
      key: 'inState',
      label: '状态',
      form: false,
      loadOptions: orgStateOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'state',
      label: '状态',
      loadOptions: orgStateOptionsLoader,
      table: true,
      type: 'select',
      width: 110,
    },
    {
      key: 'externalLegalSubjectId', label: '外部法律主体', search: true,
      loadOptions: legalSubjectOptionsLoader, remoteSearch: true, type: 'select', width: 220,
    },
    {
      key: 'inLevel',
      label: '机构级别',
      form: false,
      loadOptions: orgLevelOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'level',
      label: '机构级别',
      loadOptions: orgLevelOptionsLoader,
      type: 'select',
    },
    {
      key: 'inCategory',
      label: '机构类别',
      form: false,
      loadOptions: orgCategoryOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'category',
      label: '机构类别',
      loadOptions: orgCategoryOptionsLoader,
      type: 'select',
    },
    {
      key: 'areaCode',
      label: '区域编码',
      loadOptions: areaOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
    },
    { key: 'shortName', label: '简称', table: true, width: 120 },
    {
      key: 'confidentialLevel',
      label: '机密等级',
      loadOptions: confidentialLevelOptionsLoader,
      search: true,
      table: true,
      type: 'select',
      valueType: 'number',
      width: 120,
    },
    {
      key: 'gteExpiredTime',
      label: '到期时间开始',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'lteExpiredTime',
      label: '到期时间结束',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'expiredTime',
      label: '到期时间',
      table: true,
      type: 'datetime',
      width: 180,
    },
    { key: 'logo', label: 'Logo', table: true, type: 'image', width: 90 },
    { key: 'bankName', label: '开户银行名称', complexGroupKey: 'bank-account' },
    { key: 'bankBranchCode', label: '开户银行网点编码', complexGroupKey: 'bank-account' },
    { key: 'bankAccountName', label: '银行账号名称', complexGroupKey: 'bank-account' },
    { key: 'bankAccountNo', label: '银行账号', complexGroupKey: 'bank-account' },
    { key: 'orderCode', label: '排序代码', layoutNewRow: true, type: 'number' },
    { key: 'exInfo', label: '扩展信息', type: 'json' },
    {
      key: 'enable',
      label: '是否启用',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    { key: 'remark', label: '备注', type: 'textarea' },
  ],
  modalWidth: 1120,
  title: '机构管理',
};
