import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { fundAccountService } from '../../api/fund-account-service';
import {
  DEFAULT_CRUD_MODAL_WIDTH,
  buildDictOptionsLoader,
  buildEnumOptionsLoader,
  tenantOptionsLoader,
} from '../api-module';

const fundAccountStatusOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.FundAccount$Status',
);
const currencyTypeOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.enums.CurrencyType',
);
const confidentialLevelOptionsLoader = buildEnumOptionsLoader(
  'com.levin.commons.rbac.ConfidentialLevel',
);
const currencyCodeOptionsLoader = buildDictOptionsLoader('CurrencyCode');

export const pageMeta = {
  name: 'FundAccount',
  title: '资金账户管理',
  description: '维护资金账户。',
} as const;

export const fundAccountPageCrudConfig: CrudPageConfig = {
  apiBase: '/FundAccount',
  apiService: fundAccountService,
  defaultFormValues: {
    editable: true,
    enable: true,
    orderCode: 100,
    status: 'Normal',
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      layoutGroup: 'basic',
      layoutGroupTitle: '账户信息',
      layoutOrder: 5,
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForPlatformUser: true,
    },
    {
      key: '__tenant',
      detail: false,
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForPlatformUser: true,
      width: 180,
    },
    {
      key: 'id',
      label: '账户ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'name',
      label: '账户名称',
      layoutGroup: 'basic',
      layoutOrder: 10,
      required: true,
      search: true,
      table: true,
      width: 160,
    },
    {
      key: 'inStatus',
      label: '账户状态',
      form: false,
      loadOptions: fundAccountStatusOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'status',
      label: '账户状态',
      layoutGroup: 'basic',
      layoutOrder: 20,
      loadOptions: fundAccountStatusOptionsLoader,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'inCurrencyType',
      label: '货币类型',
      form: false,
      loadOptions: currencyTypeOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'currencyType',
      label: '货币类型',
      layoutGroup: 'basic',
      layoutOrder: 30,
      disabledOnEdit: true,
      loadOptions: currencyTypeOptionsLoader,
      omitOnEdit: true,
      required: true,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'currencyCode',
      label: '货币代码',
      layoutGroup: 'basic',
      layoutOrder: 40,
      disabledOnEdit: true,
      loadOptions: currencyCodeOptionsLoader,
      omitOnEdit: true,
      required: true,
      search: true,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'balance',
      label: '可用余额',
      layoutGroup: 'business',
      layoutGroupTitle: '资金信息',
      layoutOrder: 10,
      table: true,
      type: 'number',
      width: 120,
    },
    {
      key: 'freezeBalance',
      label: '冻结余额',
      layoutGroup: 'business',
      layoutOrder: 20,
      table: true,
      type: 'number',
      width: 120,
    },
    {
      key: 'creditLimit',
      label: '授信额度',
      layoutGroup: 'business',
      layoutOrder: 30,
      table: true,
      type: 'number',
      width: 120,
    },
    {
      key: 'creditBalance',
      label: '授信余额',
      layoutGroup: 'business',
      layoutOrder: 40,
      table: true,
      type: 'number',
      width: 120,
    },
    {
      key: 'confidentialLevel',
      label: '机密等级',
      layoutGroup: 'business',
      layoutOrder: 50,
      loadOptions: confidentialLevelOptionsLoader,
      type: 'select',
      valueType: 'number',
    },
    {
      key: 'enable',
      label: '是否启用',
      layoutGroup: 'business',
      layoutOrder: 60,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      layoutGroup: 'business',
      layoutOrder: 70,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'orderCode',
      label: '排序代码',
      layoutGroup: 'business',
      layoutOrder: 80,
      type: 'number',
    },
    {
      key: 'remark',
      label: '备注',
      fullRow: true,
      layoutGroup: 'business',
      layoutOrder: 90,
      type: 'textarea',
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '资金账户管理',
};
