import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { payOrderService } from '../../api/pay-order-service';
import {
  DEFAULT_CRUD_MODAL_WIDTH,
  buildDictOptionsLoader,
  buildEnumOptionsLoader,
  payChannelCategoryOptionsLoader,
  payChannelOptionsLoader,
  tenantOptionsLoader,
} from '../api-module';

const currencyTypeOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.enums.CurrencyType',
);
const payWayOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.enums.PayWay',
);
const tradeStatusOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.enums.TradeStatus',
);
const currencyCodeOptionsLoader = buildDictOptionsLoader('CurrencyCode');

export const pageMeta = {
  name: 'PayOrder',
  title: '支付订单管理',
  description: '维护支付订单。',
} as const;

export const payOrderPageCrudConfig: CrudPageConfig = {
  apiBase: '/PayOrder',
  apiService: payOrderService,
  defaultFormValues: {
    amount: 0,
    discountAmount: 0,
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForPlatformUser: true,
    },
    {
      key: '__tenant',
      detail: false,
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForPlatformUser: true,
      width: 180,
    },
    {
      key: 'id',
      label: '订单ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'bizType',
      label: '业务类型',
      layoutGroup: 'basic',
      layoutOrder: 10,
      layoutGroupTitle: '订单信息',
      search: true,
      table: true,
      width: 140,
    },
    {
      key: 'bizObjId',
      label: '业务对象ID',
      layoutGroup: 'basic',
      layoutOrder: 20,
      table: true,
      width: 180,
    },
    {
      key: 'bizOrderNo',
      label: '业务单号',
      layoutGroup: 'basic',
      layoutOrder: 30,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'title',
      label: '订单标题',
      layoutGroup: 'basic',
      layoutOrder: 40,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'amount',
      label: '支付金额',
      layoutGroup: 'amount',
      layoutOrder: 10,
      layoutGroupTitle: '金额与币种',
      table: true,
      type: 'number',
      width: 120,
    },
    {
      key: 'discountAmount',
      label: '优惠金额',
      layoutGroup: 'amount',
      layoutOrder: 20,
      table: true,
      type: 'number',
      width: 120,
    },
    {
      key: 'inCurrencyType',
      label: '货币类型',
      form: false,
      loadOptions: currencyTypeOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'currencyType',
      label: '货币类型',
      layoutGroup: 'amount',
      layoutOrder: 30,
      loadOptions: currencyTypeOptionsLoader,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'currencyCode',
      label: '货币代码',
      layoutGroup: 'amount',
      layoutOrder: 40,
      loadOptions: currencyCodeOptionsLoader,
      search: true,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'payChannelId',
      label: '支付通道',
      layoutGroup: 'channel',
      layoutOrder: 10,
      layoutGroupTitle: '支付通道',
      loadOptions: payChannelOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
    },
    {
      key: 'inPayChannelCategory',
      label: '支付通道类别',
      form: false,
      loadOptions: payChannelCategoryOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'payChannelCategory',
      label: '支付通道类别',
      layoutGroup: 'channel',
      layoutOrder: 20,
      loadOptions: payChannelCategoryOptionsLoader,
      table: true,
      type: 'select',
      width: 140,
    },
    {
      key: 'payChannelProviderCode',
      label: '支付提供商编码',
      layoutGroup: 'channel',
      layoutOrder: 30,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'payAppName',
      label: '支付工具名称',
      layoutGroup: 'channel',
      layoutOrder: 40,
      table: true,
      width: 160,
    },
    {
      key: 'bankSerialNo',
      label: '银行流水号',
      layoutGroup: 'channel',
      layoutOrder: 50,
      maxLength: 128,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'channelOrderNo',
      label: '通道订单号',
      layoutGroup: 'channel',
      layoutOrder: 60,
      maxLength: 128,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'inPayWay',
      label: '支付方式',
      form: false,
      loadOptions: payWayOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'payWay',
      label: '支付方式',
      layoutGroup: 'channel',
      layoutOrder: 70,
      loadOptions: payWayOptionsLoader,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'inPayStatus',
      label: '支付状态',
      form: false,
      loadOptions: tradeStatusOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'payStatus',
      label: '支付状态',
      layoutGroup: 'result',
      layoutOrder: 10,
      layoutGroupTitle: '支付结果',
      loadOptions: tradeStatusOptionsLoader,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'payResultDesc',
      label: '支付结果描述',
      layoutGroup: 'result',
      layoutOrder: 20,
      fullRow: true,
      type: 'textarea',
    },
    {
      key: 'payInfo',
      label: '支付快照信息',
      layoutGroup: 'result',
      layoutOrder: 30,
      type: 'json',
    },
    {
      key: 'exchangeInfo',
      label: '换汇信息',
      layoutGroup: 'result',
      layoutOrder: 40,
      type: 'json',
    },
    {
      key: 'gtePayTime',
      label: '支付时间开始',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'ltePayTime',
      label: '支付时间结束',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'payTime',
      label: '支付成功时间',
      layoutGroup: 'result',
      layoutOrder: 50,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'deleteTimeForUnpaid',
      label: '未支付删除时间',
      layoutGroup: 'result',
      layoutOrder: 60,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '支付订单管理',
};
