import type { CrudPageConfig } from '../../shared/types';

import {
  buildDictOptionsLoader,
  buildEnumOptionsLoader,
  DEFAULT_CRUD_MODAL_WIDTH,
  languageCodeOptionsLoader,
  nationCodeOptionsLoader,
  tenantOptionsLoader,
  userOptionsLoader,
} from '../api-module';

const customerStateOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.Customer$State',
);
const customerSexOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.Customer$Sex',
);
const confidentialLevelOptionsLoader = buildEnumOptionsLoader(
  'com.levin.commons.rbac.ConfidentialLevel',
);
const customerLevelOptionsLoader = buildDictOptionsLoader(
  'com.levin.oak.base.entities.Customer.level',
);
const customerPhoneAreaCodeOptionsLoader = buildDictOptionsLoader(
  'com.levin.oak.base.entities.Customer.phoneAreaCode',
);

export const customerPageCrudConfig: CrudPageConfig = {
  apiBase: '/Customer',
  defaultFormValues: {
    editable: true,
    enable: true,
    orderCode: 100,
    state: 'Normal',
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  permissionResourceName: '客户',
  permissionTypePrefix: '系统数据-',
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForSaasUser: true,
    },
    {
      key: '__tenant',
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForSaasUser: true,
      width: 180,
    },
    {
      key: 'orgId',
      label: '所属组织',
      type: 'org-tree-select',
    },
    {
      key: 'id',
      label: '客户ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    { key: 'containsName', label: '名称', form: false, search: true },
    { key: 'name', label: '名称', required: true, table: true, width: 150 },
    { key: 'containsTelephone', label: '手机号', form: false, search: true },
    {
      key: 'loginName',
      label: '登录名',
      search: true,
      table: true,
      width: 150,
    },
    { key: 'telephone', label: '手机号', table: true, width: 140 },
    { key: 'email', label: '邮箱', search: true, table: true, width: 180 },
    { key: 'containsNickname', label: '昵称', form: false, search: true },
    { key: 'nickname', label: '昵称', table: true, width: 140 },
    {
      key: 'nationCode',
      label: '国家编码',
      loadOptions: nationCodeOptionsLoader,
      type: 'select',
    },
    {
      key: 'langCode',
      label: '语言码',
      loadOptions: languageCodeOptionsLoader,
      type: 'select',
    },
    {
      key: 'phoneAreaCode',
      label: '手机区域码',
      loadOptions: customerPhoneAreaCodeOptionsLoader,
      type: 'select',
    },
    {
      key: 'inState',
      label: '帐号状态',
      form: false,
      loadOptions: customerStateOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'state',
      label: '帐号状态',
      loadOptions: customerStateOptionsLoader,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'inSex',
      label: '性别',
      form: false,
      loadOptions: customerSexOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'sex',
      label: '性别',
      loadOptions: customerSexOptionsLoader,
      table: true,
      type: 'select',
      width: 100,
    },
    {
      key: 'inLevel',
      label: '用户等级',
      form: false,
      loadOptions: customerLevelOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
      valueType: 'number',
    },
    {
      key: 'level',
      label: '用户等级',
      loadOptions: customerLevelOptionsLoader,
      search: true,
      table: true,
      type: 'select',
      valueType: 'number',
    },
    {
      key: 'confidentialLevel',
      label: '机密等级',
      loadOptions: confidentialLevelOptionsLoader,
      search: true,
      table: true,
      type: 'select',
      valueType: 'number',
    },
    {
      key: 'gteBirthday',
      label: '出生日期开始',
      form: false,
      search: true,
      type: 'date',
    },
    {
      key: 'lteBirthday',
      label: '出生日期结束',
      form: false,
      search: true,
      type: 'date',
    },
    {
      key: 'birthday',
      label: '出生日期',
      table: true,
      type: 'date',
      width: 120,
    },
    {
      key: 'gteJoinDate',
      label: '加入时间开始',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'lteJoinDate',
      label: '加入时间结束',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'joinDate',
      label: '加入会员时间',
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'password',
      label: '登录密码',
      formEdit: false,
      placeholder: '新增时设置初始密码；编辑时留空表示不修改',
      type: 'password',
    },
    { key: 'avatar', label: '头像', type: 'image' },
    { key: 'signature', label: '个性签名', fullRow: true, type: 'textarea' },
    { key: 'pinyinName', label: '拼音名' },
    {
      key: 'referrerId',
      label: '推荐人',
      loadOptions: userOptionsLoader,
      remoteSearch: true,
      type: 'select',
    },
    {
      key: 'enable',
      label: '是否启用',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    { key: 'remark', label: '备注', type: 'textarea' },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '客户管理',
};
