import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { importExportTemplateService } from '../../api/import-export-template-service';
import {
  buildDictOptionsLoader,
  buildEnumOptionsLoader,
  DEFAULT_CRUD_MODAL_WIDTH,
  tenantOptionsLoader,
} from '../api-module';

const importExportTemplateCategoryOptionsLoader = buildDictOptionsLoader(
  'com.levin.oak.base.entities.ImportExportTemplate.category',
);
const templateTypeOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.ImportExportTemplate$TemplateType',
);
const fileTypeOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.ImportExportTemplate$FileType',
);

export const pageMeta = {
  name: 'ImportExportTemplate',
  title: '导入导出模板管理',
  description: '维护导入导出模板。',
} as const;

export const importExportTemplatePageCrudConfig: CrudPageConfig = {
  apiBase: '/ImportExportTemplate',
  apiService: importExportTemplateService,
  defaultFormValues: {
    editable: true,
    enable: true,
    fileType: 'Excel',
    orderCode: 100,
    orgShared: false,
    tenantShared: false,
    type: 'ImportAndExport',
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      layoutGroup: 'ownership',
      layoutGroupTitle: '归属信息',
      layoutOrder: 10,
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForPlatformUser: true,
    },
    {
      key: '__tenant',
      detail: false,
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForPlatformUser: true,
      width: 180,
    },
    {
      key: 'id',
      label: '模板ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    { key: 'containsName', label: '模板名称', form: false, search: true },
    { key: 'code', label: '模板编码', form: false, search: true },
    {
      key: 'inType',
      label: '模板类型',
      form: false,
      loadOptions: templateTypeOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'inFileType',
      label: '文件类型',
      form: false,
      loadOptions: fileTypeOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    { key: 'targetType', label: '目标业务类型', form: false, search: true },
    {
      key: 'inCategory',
      label: '分类',
      form: false,
      loadOptions: importExportTemplateCategoryOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    { key: 'containsGroupName', label: '分组名称', form: false, search: true },
    {
      key: 'gteCreateTime',
      label: '创建时间开始',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'lteCreateTime',
      label: '创建时间结束',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'name',
      label: '模板名称',
      layoutGroup: 'basic',
      layoutGroupTitle: '模板信息',
      layoutOrder: 10,
      required: true,
      table: true,
      width: 180,
    },
    {
      key: 'code',
      label: '模板编码',
      layoutGroup: 'basic',
      layoutOrder: 20,
      disabledOnEdit: true,
      required: true,
      table: true,
      width: 180,
    },
    {
      key: 'type',
      label: '模板类型',
      layoutGroup: 'basic',
      layoutOrder: 30,
      loadOptions: templateTypeOptionsLoader,
      required: true,
      table: true,
      type: 'select',
      width: 140,
    },
    {
      key: 'targetType',
      label: '目标业务类型',
      layoutGroup: 'basic',
      layoutOrder: 40,
      required: true,
      table: true,
      width: 220,
    },
    {
      key: 'fileType',
      label: '文件类型',
      layoutGroup: 'basic',
      layoutOrder: 50,
      loadOptions: fileTypeOptionsLoader,
      required: true,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'category',
      label: '分类',
      layoutGroup: 'basic',
      layoutOrder: 60,
      loadOptions: importExportTemplateCategoryOptionsLoader,
      table: true,
      type: 'select',
      width: 140,
    },
    { key: 'groupName', label: '分组名称', layoutGroup: 'basic', layoutOrder: 70, table: true, width: 140 },
    {
      key: 'templateFileResId',
      label: '模板文件资源ID',
      layoutGroup: 'media',
      layoutGroupTitle: '模板文件',
      layoutOrder: 10,
      table: true,
      width: 180,
    },
    {
      key: 'templateFileUrl',
      label: '模板文件地址',
      layoutGroup: 'media',
      layoutOrder: 20,
      span: 2,
      table: true,
      width: 260,
    },
    { key: 'orderCode', label: '排序代码', layoutGroup: 'business', layoutGroupTitle: '状态设置', layoutOrder: 10, type: 'number' },
    {
      key: 'config',
      label: '配置',
      layoutGroup: 'extension',
      layoutGroupTitle: '模板配置',
      layoutOrder: 10,
      type: 'json',
    },
    {
      key: 'tenantShared',
      label: '租户共享',
      layoutGroup: 'business',
      layoutOrder: 20,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'orgShared',
      label: '组织共享',
      layoutGroup: 'business',
      layoutOrder: 30,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'enable',
      label: '是否启用',
      layoutGroup: 'business',
      layoutOrder: 40,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      layoutGroup: 'business',
      layoutOrder: 50,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    { key: 'remark', label: '备注', fullRow: true, layoutGroup: 'remark', layoutGroupTitle: '备注信息', layoutOrder: 10, type: 'textarea' },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '导入导出模板管理',
};
