import type { CrudPageConfig } from '../../shared/types';

import { DEFAULT_CRUD_MODAL_WIDTH, tenantOptionsLoader } from '../api-module';

export const brandPageCrudConfig: CrudPageConfig = {
  apiBase: '/Brand',
  defaultFormValues: {
    editable: true,
    enable: true,
    orderCode: 100,
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  permissionResourceName: '品牌',
  permissionTypePrefix: '系统数据-',
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      layoutGroup: 'ownership',
      layoutOrder: 10,
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForSaasUser: true,
    },
    {
      key: '__tenant',
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForSaasUser: true,
      width: 180,
    },
    {
      key: 'id',
      label: '品牌ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'name',
      label: '品牌名称',
      layoutGroup: 'basic',
      layoutOrder: 10,
      required: true,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'ownerName',
      label: '持有人名称',
      layoutGroup: 'basic',
      layoutOrder: 20,
      search: true,
      table: true,
      width: 160,
    },
    {
      key: 'gteCreateTime',
      label: '创建时间开始',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'lteCreateTime',
      label: '创建时间结束',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'logo',
      label: 'Logo',
      layoutGroup: 'media',
      layoutNewRow: true,
      layoutOrder: 10,
      required: true,
      table: true,
      type: 'image',
      width: 120,
    },
    {
      key: 'bigLogo',
      label: '大图Logo',
      layoutGroup: 'media',
      layoutOrder: 20,
      type: 'image',
    },
    {
      key: 'content',
      label: '品牌内容',
      fullRow: true,
      layoutGroup: 'content',
      layoutOrder: 10,
      type: 'textarea',
    },
    {
      key: 'enable',
      label: '是否启用',
      layoutGroup: 'business',
      layoutOrder: 10,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      layoutGroup: 'business',
      layoutOrder: 20,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'orderCode',
      label: '排序代码',
      layoutGroup: 'business',
      layoutOrder: 30,
      type: 'number',
    },
    {
      key: 'remark',
      label: '备注',
      layoutGroup: 'remark',
      layoutOrder: 10,
      type: 'textarea',
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '品牌管理',
};
