import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { areaService } from '../../api/area-service';
import {
  areaOptionsLoader,
  buildEnumOptionsLoader,
  DEFAULT_CRUD_MODAL_WIDTH,
} from '../api-module';

const areaTypeOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.Area$Type',
);

export const pageMeta = {
  name: 'Area',
  title: '区域管理',
  description: '维护行政区域信息。',
} as const;

export const areaPageCrudConfig: CrudPageConfig = {
  apiBase: '/Area',
  apiService: areaService,
  defaultFormValues: {
    editable: true,
    enable: true,
    orderCode: 100,
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: 'id',
      label: '区域编码',
      layoutGroup: 'basic',
      layoutGroupTitle: '区域信息',
      layoutOrder: 10,
      disabledOnEdit: true,
      fixed: 'left',
      required: true,
      search: true,
      showIdOnCreate: true,
      table: true,
      width: 140,
    },
    { key: 'containsName', label: '名称', form: false, search: true },
    {
      key: 'code',
      label: '自定义编码',
      layoutGroup: 'basic',
      layoutOrder: 20,
      search: true,
      table: true,
      width: 140,
    },
    {
      key: 'name',
      label: '名称',
      layoutGroup: 'basic',
      layoutOrder: 30,
      required: true,
      table: true,
      width: 160,
    },
    {
      key: 'parentId',
      label: '父区域',
      layoutGroup: 'basic',
      layoutOrder: 40,
      loadOptions: areaOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
    },
    {
      key: 'inType',
      label: '类型',
      form: false,
      loadOptions: areaTypeOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'type',
      label: '类型',
      layoutGroup: 'basic',
      layoutOrder: 50,
      loadOptions: areaTypeOptionsLoader,
      required: true,
      table: true,
      type: 'select',
      width: 120,
    },
    { key: 'containsPinyinName', label: '拼音名', form: false, search: true },
    {
      key: 'pinyinName',
      label: '拼音名',
      layoutGroup: 'basic',
      layoutOrder: 60,
      table: true,
      width: 160,
    },
    {
      key: 'gteCreateTime',
      label: '创建时间开始',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'lteCreateTime',
      label: '创建时间结束',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'icon',
      label: '图标',
      layoutGroup: 'basic',
      layoutOrder: 70,
      type: 'image',
    },
    {
      key: 'enable',
      label: '是否启用',
      layoutGroup: 'business',
      layoutGroupTitle: '状态与排序',
      layoutOrder: 10,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      layoutGroup: 'business',
      layoutOrder: 20,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'orderCode',
      label: '排序代码',
      layoutGroup: 'business',
      layoutOrder: 30,
      type: 'number',
    },
    {
      key: 'remark',
      label: '备注',
      fullRow: true,
      layoutGroup: 'business',
      layoutOrder: 40,
      type: 'textarea',
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '区域管理',
};
