import type { CrudPageConfig } from '../../shared/types';

import {
  DEFAULT_CRUD_MODAL_WIDTH,
  FILE_STORAGE_SINGLE_UPLOAD_PATH,
} from '../api-module';

export const servicePluginPageCrudConfig: CrudPageConfig = {
  apiBase: '/ServicePlugin',
  defaultFormValues: {
    editable: true,
    enable: true,
    orderCode: 100,
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  listTables: [
    {
      allowCreate: true,
      allowDelete: true,
      allowEdit: true,
      allowRetrieve: true,
      key: 'list',
      label: '服务插件列表',
      listPath: '/ServicePlugin/list',
      tableName: 'default',
    },
    {
      allowCreate: false,
      allowDelete: false,
      allowEdit: false,
      allowRetrieve: false,
      key: 'list2',
      listPath: '/ServicePlugin/list2',
      name: '服务插件列表-2',
      tableName: '服务插件列表-2',
      title: '表格2',
    },
    {
      allowCreate: false,
      allowDelete: false,
      allowEdit: false,
      allowRetrieve: false,
      key: 'list3',
      listPath: '/ServicePlugin/list3',
      name: '服务插件列表-3',
      tableName: '服务插件列表-3',
      title: '表格3',
    },
  ],
  fields: [
    {
      key: 'id',
      label: '插件ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'containsName',
      label: '名称',
      form: false,
      search: true,
    },
    {
      key: 'name',
      label: '名称',
      required: true,
      table: true,
      width: 180,
    },
    {
      key: 'containsPinyinName',
      label: '拼音名',
      form: false,
      search: true,
    },
    {
      key: 'pinyinName',
      label: '拼音名',
      table: true,
      width: 160,
    },
    {
      key: 'type',
      label: '插件类型',
      search: true,
      table: true,
      width: 140,
    },
    {
      key: 'className',
      label: '插件类名',
      search: true,
      table: true,
      width: 220,
    },
    {
      key: 'logo',
      label: 'Logo',
      table: true,
      type: 'image',
      uploadPath: FILE_STORAGE_SINGLE_UPLOAD_PATH,
      width: 120,
    },
    {
      key: 'expiredTime',
      label: '到期时间',
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'enable',
      label: '是否启用',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'exInfo',
      label: '扩展信息',
      fullRow: true,
      type: 'json',
    },
    {
      key: 'remark',
      label: '备注',
      fullRow: true,
      type: 'textarea',
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  permissionResourceName: '服务插件',
  permissionTypePrefix: '专家数据-',
  title: '服务插件管理',
};
