import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { payChannelService } from '../../api/pay-channel-service';
import {
  buildDictOptionsLoader,
  buildEnumOptionsLoader,
  DEFAULT_CRUD_MODAL_WIDTH,
  payChannelAgentCodeOptionsLoader,
  payChannelCategoryOptionsLoader,
  tenantOptionsLoader,
} from '../api-module';

const currencyTypeOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.enums.CurrencyType',
);
const currencyCodeOptionsLoader = buildDictOptionsLoader('CurrencyCode');

export const pageMeta = {
  name: 'PayChannel',
  title: '支付渠道管理',
  description: '维护支付渠道配置。',
} as const;

export const payChannelPageCrudConfig: CrudPageConfig = {
  apiBase: '/PayChannel',
  apiService: payChannelService,
  defaultFormValues: {
    editable: true,
    enable: true,
    orderCode: 100,
    currencyCodeList: [],
    payWayItemList: [],
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      layoutOrder: 10,
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForPlatformUser: true,
    },
    {
      key: '__tenant',
      detail: false,
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForPlatformUser: true,
      width: 180,
    },
    {
      key: 'id',
      label: '通道ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'name',
      label: '通道名称',
      layoutGroup: 'basic',
      layoutGroupTitle: '通道信息',
      layoutOrder: 10,
      required: true,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'gteExpiredTime',
      label: '有效期开始',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'lteExpiredTime',
      label: '有效期结束',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'expiredTime',
      label: '有效期',
      layoutGroup: 'basic',
      layoutOrder: 20,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'logo',
      label: '支付通道图标',
      layoutGroup: 'basic',
      layoutOrder: 70,
      table: true,
      type: 'image',
      width: 120,
    },
    {
      key: 'inCategory',
      label: '类别',
      form: false,
      loadOptions: payChannelCategoryOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'category',
      label: '类别',
      layoutGroup: 'basic',
      layoutOrder: 30,
      loadOptions: payChannelCategoryOptionsLoader,
      required: true,
      table: true,
      type: 'select',
      width: 140,
    },
    {
      key: 'inCurrencyType',
      label: '货币类型',
      form: false,
      loadOptions: currencyTypeOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'currencyType',
      label: '货币类型',
      layoutGroup: 'basic',
      layoutOrder: 40,
      loadOptions: currencyTypeOptionsLoader,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'currencyCodeList',
      label: '支持货币代码',
      layoutGroup: 'basic',
      layoutOrder: 50,
      loadOptions: currencyCodeOptionsLoader,
      multiple: true,
      type: 'select',
    },
    {
      key: 'inAgentCode',
      label: '通道代理商',
      form: false,
      loadOptions: payChannelAgentCodeOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'agentCode',
      label: '通道代理商',
      layoutGroup: 'basic',
      layoutOrder: 60,
      loadOptions: payChannelAgentCodeOptionsLoader,
      table: true,
      type: 'select',
      width: 140,
    },
    {
      key: 'rate',
      label: '通道费率',
      layoutGroup: 'business',
      layoutGroupTitle: '商户与费率',
      layoutOrder: 10,
      table: true,
      type: 'number',
      width: 120,
    },
    {
      key: 'merchantId',
      label: '商户编码',
      layoutGroup: 'business',
      layoutOrder: 20,
      table: true,
      width: 160,
    },
    {
      key: 'merchantName',
      label: '商户名称',
      layoutGroup: 'business',
      layoutOrder: 30,
      table: true,
      width: 160,
    },
    {
      key: 'providerCode',
      label: '支付提供商',
      layoutGroup: 'business',
      layoutOrder: 40,
      required: true,
      table: true,
      width: 180,
    },
    {
      key: 'payWayItemList',
      label: '支持支付方式',
      fullRow: true,
      layoutGroup: 'content',
      layoutGroupTitle: '支付方式',
      layoutOrder: 10,
    },
    {
      key: 'detailInfo',
      label: '通道详情',
      layoutOrder: 10,
      help: '先选择支付提供商，再按其配置模型填写具体参数。密钥和证书仅填写运行时引用名。',
      type: 'json',
    },
    {
      key: 'enable',
      label: '是否启用',
      layoutGroup: 'business',
      layoutOrder: 50,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      layoutGroup: 'business',
      layoutOrder: 60,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'remark',
      label: '备注',
      fullRow: true,
      layoutOrder: 10,
      type: 'textarea',
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '支付渠道管理',
};
