import type { CrudPageConfig } from '../../shared/types';

import {
  buildEnumOptionsLoader,
  DEFAULT_CRUD_MODAL_WIDTH,
  nationCodeOptionsLoader,
  tenantOptionsLoader,
} from '../api-module';

const addressCategoryOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.Address$Category',
);

export const addressPageCrudConfig: CrudPageConfig = {
  apiBase: '/Address',
  defaultFormValues: {
    category: 'ReceiveAndSend',
    editable: true,
    enable: true,
    isDefault: false,
    orderCode: 100,
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  permissionResourceName: '地址',
  permissionTypePrefix: '业务数据-',
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForSaasUser: true,
    },
    {
      key: '__tenant',
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForSaasUser: true,
      width: 180,
    },
    {
      key: 'id',
      label: '地址ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    { key: 'containsName', label: '收寄件人姓名', form: false, search: true },
    {
      key: 'containsTelephone',
      label: '收寄件人手机号',
      form: false,
      search: true,
    },
    {
      key: 'inCategory',
      label: '地址类别',
      form: false,
      loadOptions: addressCategoryOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'nationCode',
      label: '国家编码',
      loadOptions: nationCodeOptionsLoader,
      search: true,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'provinceCode',
      label: '省编码',
      required: true,
      search: true,
      table: true,
      width: 120,
    },
    {
      key: 'cityCode',
      label: '市编码',
      required: true,
      search: true,
      table: true,
      width: 120,
    },
    {
      key: 'districtCode',
      label: '区县编码',
      required: true,
      search: true,
      table: true,
      width: 120,
    },
    { key: 'postalCode', label: '邮编', search: true, table: true, width: 120 },
    {
      key: 'gteCreateTime',
      label: '创建时间开始',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'lteCreateTime',
      label: '创建时间结束',
      form: false,
      search: true,
      type: 'datetime',
    },
    { key: 'name', label: '收寄件人姓名', table: true, width: 140 },
    { key: 'telephone', label: '收寄件人手机号', table: true, width: 140 },
    {
      key: 'category',
      label: '地址类别',
      loadOptions: addressCategoryOptionsLoader,
      table: true,
      type: 'select',
      width: 140,
    },
    {
      key: 'address',
      label: '详细地址',
      fullRow: true,
      required: true,
      type: 'textarea',
    },
    {
      key: 'isDefault',
      label: '是否默认地址',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 120,
    },
    {
      key: 'enable',
      label: '是否启用',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    { key: 'orderCode', label: '排序代码', type: 'number' },
    { key: 'remark', label: '备注', type: 'textarea' },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '地址管理',
};
