import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { brandService } from '../../api/brand-service';
import { DEFAULT_CRUD_MODAL_WIDTH, tenantOptionsLoader } from '../api-module';

export const pageMeta = {
  name: 'Brand',
  title: '品牌管理',
  description: '维护品牌信息。',
} as const;

export const brandPageCrudConfig: CrudPageConfig = {
  apiBase: '/Brand',
  apiService: brandService,
  defaultFormValues: {
    editable: true,
    enable: true,
    orderCode: 100,
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      layoutGroup: 'basic',
      layoutGroupTitle: '品牌信息',
      layoutOrder: 5,
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForPlatformUser: true,
    },
    {
      key: '__tenant',
      detail: false,
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForPlatformUser: true,
      width: 180,
    },
    {
      key: 'orgId',
      label: '所属组织',
      layoutGroup: 'basic',
      layoutOrder: 6,
      type: 'org-tree-select',
    },
    {
      key: 'id',
      label: '品牌ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'name',
      label: '品牌名称',
      layoutGroup: 'basic',
      layoutOrder: 10,
      required: true,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'ownerName',
      label: '持有人名称',
      layoutGroup: 'basic',
      layoutOrder: 20,
      search: true,
      table: true,
      width: 160,
    },
    {
      key: 'gteCreateTime',
      label: '创建时间开始',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'lteCreateTime',
      label: '创建时间结束',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'logo',
      label: 'Logo',
      layoutGroup: 'media',
      layoutGroupTitle: '品牌素材',
      layoutNewRow: true,
      layoutOrder: 10,
      required: true,
      table: true,
      type: 'image',
      width: 120,
    },
    {
      key: 'shortcutIcon',
      label: '快捷图标',
      layoutGroup: 'media',
      layoutOrder: 20,
      type: 'image',
    },
    {
      key: 'title',
      label: '标题',
      layoutGroup: 'basic',
      layoutOrder: 30,
    },
    {
      key: 'titleImg',
      label: '标题图',
      layoutGroup: 'media',
      layoutOrder: 40,
      type: 'image',
    },
    {
      key: 'bannerImg',
      label: '横幅图',
      layoutGroup: 'media',
      layoutOrder: 50,
      type: 'image',
    },
    {
      key: 'mainImg',
      label: '主图',
      layoutGroup: 'media',
      layoutOrder: 60,
      type: 'image',
    },
    {
      key: 'bigImg',
      label: '大图',
      layoutGroup: 'media',
      layoutOrder: 70,
      type: 'image',
    },
    {
      key: 'content',
      label: '品牌内容',
      fullRow: true,
      layoutGroup: 'basic',
      layoutOrder: 40,
      type: 'textarea',
    },
    {
      key: 'enable',
      label: '是否启用',
      layoutGroup: 'business',
      layoutGroupTitle: '品牌状态',
      layoutOrder: 10,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      layoutGroup: 'business',
      layoutOrder: 20,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'orderCode',
      label: '排序代码',
      layoutGroup: 'business',
      layoutOrder: 30,
      type: 'number',
    },
    {
      key: 'remark',
      label: '备注',
      fullRow: true,
      layoutGroup: 'business',
      layoutOrder: 40,
      type: 'textarea',
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '品牌管理',
};
