import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { dictService } from '../../api/dict-service';

import { tenantOptionsLoader } from '../api-module';

export const dictTitle = '数据字典管理';

export const dictTypeOptions = [
  { label: '系统', value: 'System' },
  { label: '自定义', value: 'Custom' },
];

export const pageMeta = {
  name: 'Dict',
  title: '数据字典管理',
  description: '维护系统数据字典。',
} as const;

export const dictPageCrudConfig: CrudPageConfig = {
  apiBase: '/Dict',
  apiService: dictService,
  defaultFormValues: {
    editable: true,
    enable: true,
    itemList: [],
    orderCode: 100,
    type: 'Custom',
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      layoutGroup: 'ownership',
      layoutOrder: 10,
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForPlatformUser: true,
    },
    {
      key: '__tenant',
      detail: false,
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForPlatformUser: true,
      width: 180,
    },
    {
      key: 'id',
      label: '字典ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    { key: 'containsName', label: '字典名称', form: false, search: true },
    { key: 'code', label: '字典编码', form: false, search: true },
    {
      key: 'inType',
      label: '字典类型',
      form: false,
      multiple: true,
      options: dictTypeOptions,
      search: true,
      type: 'select',
    },
    { key: 'category', label: '类别', form: false, search: true },
    { key: 'groupName', label: '分组', form: false, search: true },
    {
      key: 'gteCreateTime',
      label: '创建时间开始',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'lteCreateTime',
      label: '创建时间结束',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'name',
      label: '字典名称',
      layoutGroup: 'basic',
      layoutOrder: 10,
      required: true,
      table: true,
      width: 160,
    },
    {
      key: 'code',
      label: '字典编码',
      disabledOnEdit: true,
      layoutGroup: 'basic',
      layoutOrder: 20,
      required: true,
      table: true,
      width: 180,
    },
    {
      key: 'type',
      label: '字典类型',
      layoutGroup: 'basic',
      layoutOrder: 30,
      options: dictTypeOptions,
      required: true,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'category',
      label: '类别',
      layoutGroup: 'basic',
      layoutOrder: 40,
      table: true,
      width: 140,
    },
    {
      key: 'groupName',
      label: '分组',
      layoutGroup: 'basic',
      layoutOrder: 50,
      table: true,
      width: 140,
    },
    {
      key: 'itemList',
      label: '字典项',
      fullRow: true,
      layoutGroup: 'content',
      layoutNewRow: true,
      layoutOrder: 10,
    },
    {
      key: 'orderCode',
      label: '排序代码',
      layoutGroup: 'business',
      layoutNewRow: true,
      layoutOrder: 10,
      type: 'number',
    },
    {
      key: 'enable',
      label: '是否启用',
      layoutGroup: 'business',
      layoutOrder: 20,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      layoutGroup: 'business',
      layoutOrder: 30,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'remark',
      label: '备注',
      fullRow: true,
      layoutGroup: 'remark',
      layoutOrder: 10,
      type: 'textarea',
    },
  ],
  formMaxColumns: 2,
  modalWidth: 960,
  title: dictTitle,
};
