import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { tenantService } from '../../api/tenant-service';
import {
  confidentialLevelOptionsLoader,
  currencyCodeOptionsLoader,
  languageCodeOptionsLoader,
  nationCodeOptionsLoader,
  tenantLevelOptionsLoader,
  tenantTypeOptionsLoader,
} from '../api-module';
import { siteInfoFormFields, transformSiteInfoSubmit } from '../site-info-form';

export const pageMeta = {
  name: 'Tenant',
  title: '租户管理',
  description: '维护租户信息。',
} as const;

export const tenantPageCrudConfig: CrudPageConfig = {
  apiBase: '/Tenant',
  apiService: tenantService,
  defaultFormValues: {
    editable: true,
    enable: true,
    orderCode: 100,
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  description:
    '租户创建仍走后端初始化流程，前端这里只接常用字段，默认交给业务服务完成初始化。',
  fields: [
    {
      key: 'id',
      label: '租户ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    { key: 'containsName', label: '租户名称', form: false, search: true },
    {
      key: 'name',
      label: '租户名称',
      layoutGroup: 'basic',
      layoutGroupTitle: '租户信息',
      layoutOrder: 10,
      required: true,
      table: true,
      width: 160,
    },
    {
      key: 'inType',
      label: '租户类型',
      form: false,
      loadOptions: tenantTypeOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'type',
      label: '租户类型',
      layoutGroup: 'basic',
      layoutOrder: 20,
      loadOptions: tenantTypeOptionsLoader,
      table: true,
      type: 'select',
      width: 130,
    },
    {
      key: 'inLevel',
      label: '租户级别',
      form: false,
      loadOptions: tenantLevelOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'level',
      label: '租户级别',
      layoutGroup: 'basic',
      layoutOrder: 30,
      loadOptions: tenantLevelOptionsLoader,
      table: true,
      type: 'select',
      width: 130,
    },
    {
      key: 'confidentialLevel',
      label: '机密等级',
      layoutGroup: 'basic',
      layoutOrder: 40,
      loadOptions: confidentialLevelOptionsLoader,
      search: true,
      table: true,
      type: 'select',
      valueType: 'number',
      width: 120,
    },
    {
      key: 'sysName',
      label: '系统名称',
      layoutGroup: 'basic',
      layoutOrder: 50,
      search: true,
      table: true,
      width: 160,
    },
    { key: 'code', label: '企业信用编码', layoutGroup: 'basic', layoutOrder: 60, search: true, table: true },
    { key: 'tenantKey', label: '租户Key', layoutGroup: 'basic', layoutOrder: 70, table: true, width: 150 },
    {
      key: 'inNationCode',
      label: '国家编码',
      form: false,
      loadOptions: nationCodeOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'nationCode',
      label: '国家编码',
      layoutGroup: 'basic',
      layoutOrder: 80,
      loadOptions: nationCodeOptionsLoader,
      type: 'select',
    },
    {
      key: 'inCurrencyCode',
      label: '货币编码',
      form: false,
      loadOptions: currencyCodeOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'currencyCode',
      label: '货币编码',
      layoutGroup: 'basic',
      layoutOrder: 90,
      loadOptions: currencyCodeOptionsLoader,
      type: 'select',
    },
    {
      key: 'inLanguageCode',
      label: '语言编码',
      form: false,
      loadOptions: languageCodeOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'languageCode',
      label: '语言编码',
      layoutGroup: 'basic',
      layoutOrder: 100,
      loadOptions: languageCodeOptionsLoader,
      type: 'select',
    },
    { key: 'sysLogo', label: '系统Logo', layoutGroup: 'basic', layoutOrder: 110, type: 'image' },
    ...siteInfoFormFields,
    {
      key: 'balance',
      label: '帐号余额',
      layoutGroup: 'license',
      layoutNewRow: true,
      layoutOrder: 10,
      table: true,
      type: 'number',
    },
    { key: 'licenseCnt', label: '总许可数', layoutGroup: 'license', layoutOrder: 20, type: 'number' },
    { key: 'remainingLicenseCnt', label: '剩余许可数', layoutGroup: 'license', layoutOrder: 30, type: 'number' },
    {
      key: 'gteExpiredTime',
      label: '到期时间开始',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'lteExpiredTime',
      label: '到期时间结束',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'expiredTime',
      label: '到期时间',
      layoutGroup: 'license',
      layoutOrder: 40,
      table: true,
      type: 'datetime',
      width: 180,
    },
    { key: 'contractPerson', label: '联系人', layoutGroup: 'contact', layoutOrder: 10, table: true },
    { key: 'contractPhone', label: '联系电话', layoutGroup: 'contact', layoutOrder: 20, table: true },
    { key: 'appId', label: '应用ID', layoutGroup: 'application', layoutOrder: 10 },
    { key: 'appAuthDomain', label: '应用授权域名', layoutGroup: 'application', layoutOrder: 20 },
    { key: 'appSecret', label: '应用密钥', layoutGroup: 'application', layoutNewRow: true, layoutOrder: 30, span: 2, type: 'textarea' },
    { key: 'encryptKey', label: '租户密钥', layoutGroup: 'application', layoutOrder: 40, type: 'textarea' },
    { key: 'uiExInfo', label: '前端展示扩展信息', layoutGroup: 'extension', layoutOrder: 10, type: 'json' },
    { key: 'exInfo', label: '扩展信息', layoutGroup: 'extension', layoutOrder: 20, type: 'json' },
    { key: 'orderCode', label: '排序代码', layoutGroup: 'status', layoutNewRow: true, layoutOrder: 10, type: 'number' },
    {
      key: 'enable',
      label: '是否启用',
      layoutGroup: 'status',
      layoutOrder: 20,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      layoutGroup: 'status',
      layoutOrder: 30,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    { key: 'remark', label: '备注', fullRow: true, layoutGroup: 'remark', layoutOrder: 10, type: 'textarea' },
  ],
  formMaxColumns: 3,
  modalWidth: 1120,
  title: '租户管理',
  transformSubmit: transformSiteInfoSubmit,
};
