import type { CrudPageConfig } from '../../shared/types';

import {
  buildEnumOptionsLoader,
  DEFAULT_CRUD_MODAL_WIDTH,
  FILE_STORAGE_MULTI_UPLOAD_PATH,
  FILE_STORAGE_SINGLE_UPLOAD_PATH,
  tenantOptionsLoader,
} from '../api-module';

const fileResTypeOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.FileRes$Type',
);
const confidentialLevelOptionsLoader = buildEnumOptionsLoader(
  'com.levin.commons.rbac.ConfidentialLevel',
);

export const fileResPageCrudConfig: CrudPageConfig = {
  apiBase: '/FileRes',
  defaultFormValues: {
    editable: true,
    enable: true,
    orderCode: 100,
    paths: [],
    tagList: [],
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForSaasUser: true,
    },
    {
      key: '__tenant',
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForSaasUser: true,
      width: 180,
    },
    {
      key: 'id',
      label: '文件ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    {
      key: 'name',
      label: '文件名称',
      required: true,
      search: true,
      table: true,
      width: 220,
    },
    {
      key: 'type',
      label: '文件类型',
      loadOptions: fileResTypeOptionsLoader,
      search: true,
      table: true,
      type: 'select',
      width: 140,
    },
    {
      key: 'category',
      label: '类别',
      search: true,
      table: true,
      width: 140,
    },
    {
      key: 'mimeType',
      label: 'Mime类型',
      table: true,
      width: 160,
    },
    {
      key: 'bizObjId',
      label: '业务对象ID',
      table: true,
      width: 180,
    },
    {
      key: 'coverUrl',
      label: '封面图',
      table: true,
      type: 'image',
      uploadPath: FILE_STORAGE_SINGLE_UPLOAD_PATH,
      width: 120,
    },
    {
      key: 'paths',
      label: '文件路径',
      fullRow: true,
      multiple: true,
      type: 'file',
      uploadPath: FILE_STORAGE_MULTI_UPLOAD_PATH,
    },
    {
      key: 'tagList',
      label: '标签列表',
      fullRow: true,
      type: 'tags',
    },
    {
      key: 'confidentialLevel',
      label: '机密等级',
      loadOptions: confidentialLevelOptionsLoader,
      type: 'select',
      valueType: 'number',
    },
    {
      key: 'publishable',
      label: '公网发布',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'deleted',
      label: '已删除',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'tenantShared',
      label: '租户共享',
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'orgShared',
      label: '组织共享',
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'enable',
      label: '是否启用',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'exInfo',
      label: '扩展信息',
      fullRow: true,
      type: 'json',
    },
    {
      key: 'remark',
      label: '备注',
      fullRow: true,
      type: 'textarea',
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
  ],
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  permissionResourceName: '文件资源库',
  permissionTypePrefix: '通用数据-',
  title: '文件资源管理',
};
