import type { CrudPageConfig } from '@levin/admin-framework/framework-commons/shared/types';

import { isSuperAdminUser } from '@levin/admin-framework/framework-commons/shared/user-identity';

import { userSettingService } from '../../api/user-setting-service';
import {
  buildEnumOptionsLoader,
  DEFAULT_CRUD_MODAL_WIDTH,
  tenantOptionsLoader,
  userOptionsLoader,
} from '../api-module';
import { transformSettingCrudSubmit } from '../setting-crud-submit';

const userSettingValueTypeOptionsLoader = buildEnumOptionsLoader(
  'com.levin.oak.base.entities.Setting$ValueType',
);

export const pageMeta = {
  name: 'UserSetting',
  title: '用户设置管理',
  description: '维护用户设置。',
} as const;

export const userSettingPageCrudConfig: CrudPageConfig = {
  apiBase: '/UserSetting',
  apiService: userSettingService,
  defaultFormValues: {
    editable: true,
    enable: true,
    nullable: true,
    orderCode: 100,
    valueType: 'Text',
  },
  defaultQuery: {
    pageIndex: 1,
    pageSize: 10,
  },
  fields: [
    {
      key: 'tenantId',
      label: '归属租户',
      layoutGroup: 'basic',
      layoutGroupTitle: '设置标识与归属',
      layoutOrder: 10,
      loadOptions: tenantOptionsLoader,
      remoteSearch: true,
      search: true,
      type: 'select',
      visibleForPlatformUser: true,
    },
    {
      key: '__tenant',
      detail: false,
      label: '归属租户',
      fixed: 'left',
      form: false,
      table: true,
      type: 'tenant',
      visibleForPlatformUser: true,
      width: 180,
    },
    {
      key: 'ownerId',
      label: '所属用户',
      layoutGroup: 'basic',
      layoutOrder: 20,
      loadOptions: userOptionsLoader,
      remoteSearch: true,
      type: 'select',
    },
    {
      key: 'id',
      label: '设置ID',
      fixed: 'left',
      form: false,
      search: true,
      table: true,
      width: 180,
    },
    { key: 'containsGroupName', label: '分组名称', form: false, search: true },
    { key: 'code', label: '编码', form: false, search: true },
    { key: 'categoryName', label: '分类名称', form: false, search: true },
    {
      key: 'inValueType',
      label: '值类型',
      form: false,
      loadOptions: userSettingValueTypeOptionsLoader,
      multiple: true,
      search: true,
      type: 'select',
    },
    {
      key: 'gteCreateTime',
      label: '创建时间开始',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'lteCreateTime',
      label: '创建时间结束',
      form: false,
      search: true,
      type: 'datetime',
    },
    {
      key: 'groupName',
      label: '分组名称',
      layoutGroup: 'basic',
      layoutOrder: 30,
      table: true,
      width: 160,
    },
    {
      key: 'code',
      label: '编码',
      layoutGroup: 'basic',
      layoutOrder: 40,
      required: true,
      table: true,
      width: 180,
    },
    {
      key: 'categoryName',
      label: '分类名称',
      layoutGroup: 'basic',
      layoutOrder: 50,
      required: true,
      table: true,
      width: 140,
    },
    {
      key: 'icon',
      label: '图标',
      layoutGroup: 'basic',
      layoutOrder: 60,
      type: 'image',
    },
    {
      key: 'valueType',
      label: '值类型',
      layoutGroup: 'content',
      layoutOrder: 10,
      loadOptions: userSettingValueTypeOptionsLoader,
      table: true,
      type: 'select',
      width: 120,
    },
    {
      key: 'editor',
      label: '值编辑器',
      disabledOnEdit: ({ userInfo }) => !isSuperAdminUser(userInfo),
      fullRow: true,
      layoutGroup: 'content',
      layoutNewRow: true,
      layoutOrder: 20,
      type: 'text',
    },
    {
      key: 'valueContent',
      label: '值',
      fullRow: true,
      layoutGroup: 'content',
      layoutOrder: 30,
      type: 'textarea',
    },
    {
      key: 'nullable',
      label: '值是否可空',
      layoutGroup: 'content',
      layoutOrder: 40,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 120,
    },
    {
      key: 'inputPlaceholder',
      label: '输入占位提示',
      fullRow: true,
      layoutGroup: 'content',
      layoutOrder: 50,
      type: 'textarea',
    },
    {
      key: 'orderCode',
      label: '排序代码',
      layoutGroup: 'status',
      layoutOrder: 10,
      type: 'number',
    },
    {
      key: 'enable',
      label: '是否启用',
      layoutGroup: 'status',
      layoutOrder: 20,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 100,
    },
    {
      key: 'editable',
      label: '是否可编辑',
      layoutGroup: 'status',
      layoutOrder: 30,
      search: true,
      table: true,
      type: 'switch',
      valueType: 'boolean',
      width: 110,
    },
    {
      key: 'createTime',
      label: '创建时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'lastUpdateTime',
      label: '更新时间',
      form: false,
      table: true,
      type: 'datetime',
      width: 180,
    },
    {
      key: 'remark',
      label: '备注',
      fullRow: true,
      layoutOrder: 10,
      type: 'textarea',
    },
  ],
  formMaxColumns: 3,
  modalWidth: DEFAULT_CRUD_MODAL_WIDTH,
  title: '用户设置管理',
  transformSubmit: transformSettingCrudSubmit,
};
